const cronicas1 = {
  1: {
    1: " Adán, Set, Enós,\n",
    2: " Cainán, Mahalaleel, Jared,\n",
    3: " Enoc, Matusalén, Lamec,\n",
    4: " Noé, Sem, Cam y Jafet.\n",
    5: " Los hijos de Jafet: Gomer, Magog, Madai, Javán, Tubal, Mesec y Tiras.\n",
    6: " Los hijos de Gomer: Askenaz, Rifat y Togarma.\n",
    7: " Los hijos de Javán: Elisa, Tarsis, Quitim y Dodanim.\n",
    8: " Los hijos de Cam: Cus, Mizraim, Fut y Canaán.\n",
    9: " Los hijos de Cus: Seba, Havila, Sabta, Raama y Sabteca. Y los hijos de Raama: Seba y Dedán.\n",
    10: " Cus engendró a Nimrod; éste llegó a ser poderoso en la tierra.\n",
    11: " Mizraim engendró a Ludim, Anamim, Lehabim, Naftuhim,\n",
    12: " Patrusim y Casluhim; de éstos salieron los filisteos y los caftoreos.\n",
    13: " Canaán engendró a Sidón su primogénito, y a Het,\n",
    14: " al jebuseo, al amorreo, al gergeseo,\n",
    15: " al heveo, al araceo, al sineo,\n",
    16: " al arvadeo, al zemareo y al hamateo.\n",
    17: " Los hijos de Sem: Elam, Asur, Arfaxad, Lud, Aram, Uz, Hul, Geter y Mesec.\n",
    18: " Arfaxad engendró a Sela, y Sela engendró a Heber.\n",
    19: " Y a Heber nacieron dos hijos; el nombre del uno fue Peleg, por cuanto en sus días fue dividida la tierra; y el nombre de su hermano fue Joctán.\n",
    20: " Joctán engendró a Almodad, Selef, Hazar-mavet y Jera.\n",
    21: " A Adoram también, a Uzal, Dicla,\n",
    22: " Ebal, Abimael, Seba,\n",
    23: " Ofir, Havila y Jobab; todos hijos de Joctán.\n",
    24: " Sem, Arfaxad, Sela,\n",
    25: " Heber, Peleg, Reu,\n",
    26: " Serug, Nacor, Taré,\n",
    27: " y Abram, el cual es Abraham.\n",
    28: " Los hijos de Abraham: Isaac e Ismael.\n",
    29: " Y estas son sus descendencias: el primogénito de Ismael, Nebaiot; después Cedar, Adbeel, Mibsam,\n",
    30: " Misma, Duma, Massa, Hadad, Tema,\n",
    31: " Jetur, Nafis y Cedema; éstos son los hijos de Ismael.\n",
    32: " Y Cetura, concubina de Abraham, dio a luz a Zimram, Jocsán, Medán, Madián, Isbac y Súa. Los hijos de Jocsán: Seba y Dedán.\n",
    33: " Los hijos de Madián: Efa, Efer, Hanoc, Abida y Elda; todos éstos fueron hijos de Cetura.\n",
    34: " Abraham engendró a Isaac, y los hijos de Isaac fueron Esaú e Israel.\n",
    35: " Los hijos de Esaú: Elifaz, Reuel, Jeús, Jaalam y Coré.\n",
    36: " Los hijos de Elifaz: Temán, Omar, Zefo, Gatam, Cenaz, Timna y Amalec.\n",
    37: " Los hijos de Reuel: Nahat, Zera, Sama y Miza.\n",
    38: " Los hijos de Seir: Lotán, Sobal, Zibeón, Aná, Disón, Ezer y Disán.\n",
    39: " Los hijos de Lotán: Hori y Homam; y Timna fue hermana de Lotán.\n",
    40: " Los hijos de Sobal: Alván, Manahat, Ebal, Sefo y Onam. Los hijos de Zibeón: Aja y Aná.\n",
    41: " Disón fue hijo de Aná; y los hijos de Disón: Amram, Esbán, Itrán y Querán.\n",
    42: " Los hijos de Ezer: Bilhán, Zaaván y Jaacán. Los hijos de Disán: Uz y Arán.\n",
    43: " Y estos son los reyes que reinaron en la tierra de Edom, antes que reinase rey sobre los hijos de Israel: Bela hijo de Beor; y el nombre de su ciudad fue Dinaba.\n",
    44: " Muerto Bela, reinó en su lugar Jobab hijo de Zera, de Bosra.\n",
    45: " Y muerto Jobab, reinó en su lugar Husam, de la tierra de los temanitas.\n",
    46: " Muerto Husam, reinó en su lugar Hadad hijo de Bedad, el que derrotó a Madián en el campo de Moab; y el nombre de su ciudad fue Avit.\n",
    47: " Muerto Hadad, reinó en su lugar Samla de Masreca.\n",
    48: " Muerto también Samla, reinó en su lugar Saúl de Rehobot, que está junto al Eufrates.\n",
    49: " Y muerto Saúl, reinó en su lugar Baal-hanán hijo de Acbor.\n",
    50: " Muerto Baal-hanán, reinó en su lugar Hadad, el nombre de cuya ciudad fue Pai; y el nombre de su mujer, Mehetabel hija de Matred, hija de Mezaab.\n",
    51: " Muerto Hadad, sucedieron en Edom los jefes Timna, Alva, Jetet,\n",
    52: " Aholibama, Ela, Pinón,\n",
    53: " Cenaz, Temán, Mibzar,\n",
    54: " Magdiel e Iram. Estos fueron los jefes de Edom. ",
  },
};
export default cronicas1;
