const habacuc = {
  1: {
    1: " La profecía que vio el profeta Habacuc.\n",
    2: " ¿Hasta cuándo, oh Jehová, clamaré, y no oirás; y daré voces a ti a causa de la violencia, y no salvarás?\n",
    3: " ¿Por qué me haces ver iniquidad, y haces que vea molestia? Destrucción y violencia están delante de mí, y pleito y contienda se levantan.\n",
    4: " Por lo cual la ley es debilitada, y el juicio no sale según la verdad; por cuanto el impío asedia al justo, por eso sale torcida la justicia.\n",
    5: " Mirad entre las naciones, y ved, y asombraos; porque haré una obra en vuestros días, que aun cuando se os contare, no la creeréis.\n",
    6: " Porque he aquí, yo levanto a los caldeos, nación cruel y presurosa, que camina por la anchura de la tierra para poseer las moradas ajenas.\n",
    7: " Formidable es y terrible; de ella misma procede su justicia y su dignidad.\n",
    8: " Sus caballos serán más ligeros que leopardos, y más feroces que lobos nocturnos, y sus jinetes se multiplicarán; vendrán de lejos sus jinetes, y volarán como águilas que se apresuran a devorar.\n",
    9: " Toda ella vendrá a la presa; el terror va delante de ella, y recogerá cautivos como arena.\n",
    10: " Escarnecerá a los reyes, y de los príncipes hará burla; se reirá de toda fortaleza, y levantará terraplén y la tomará.\n",
    11: " Luego pasará como el huracán, y ofenderá atribuyendo su fuerza a su dios.\n",
    12: " ¿No eres tú desde el principio, oh Jehová, Dios mío, Santo mío? No moriremos. Oh Jehová, para juicio lo pusiste; y tú, oh Roca, lo fundaste para castigar.\n",
    13: " Muy limpio eres de ojos para ver el mal, ni puedes ver el agravio; ¿por qué ves a los menospreciadores, y callas cuando destruye el impío al más justo que él,\n",
    14: " y haces que sean los hombres como los peces del mar, como reptiles que no tienen quien los gobierne?\n",
    15: " Sacará a todos con anzuelo, los recogerá con su red, y los juntará en sus mallas; por lo cual se alegrará y se regocijará.\n",
    16: " Por esto hará sacrificios a su red, y ofrecerá sahumerios a sus mallas; porque con ellas engordó su porción, y engrasó su comida.\n",
    17: " ¿Vaciará por eso su red, y no tendrá piedad de aniquilar naciones continuamente? ",
  },
  2: {
    1: " Sobre mi guarda estaré, y sobre la fortaleza afirmaré el pie, y velaré para ver lo que se me dirá, y qué he de responder tocante a mi queja.\n",
    2: " Y Jehová me respondió, y dijo: Escribe la visión, y declárala en tablas, para que corra el que leyere en ella.\n",
    3: " Aunque la visión tardará aún por un tiempo, mas se apresura hacia el fin, y no mentirá; aunque tardare, espéralo, porque sin duda vendrá, no tardará.\n",
    4: " He aquí que aquel cuya alma no es recta, se enorgullece; mas el justo por su fe vivirá.\n",
    5: " Y también, el que es dado al vino es traicionero, hombre soberbio, que no permanecerá; ensanchó como el Seol su alma, y es como la muerte, que no se saciará; antes reunió para sí todas las gentes, y juntó para sí todos los pueblos.\n",
    6: " ¿No han de levantar todos éstos refrán sobre él, y sarcasmos contra él? Dirán: ¡Ay del que multiplicó lo que no era suyo! ¿Hasta cuándo había de acumular sobre sí prenda tras prenda?\n",
    7: " ¿No se levantarán de repente tus deudores, y se despertarán los que te harán temblar, y serás despojo para ellos?\n",
    8: " Por cuanto tú has despojado a muchas naciones, todos los otros pueblos te despojarán, a causa de la sangre de los hombres, y de los robos de la tierra, de las ciudades y de todos los que habitan en ellas.\n",
    9: " ¡Ay del que codicia injusta ganancia para su casa, para poner en alto su nido, para escaparse del poder del mal!\n",
    10: " Tomaste consejo vergonzoso para tu casa, asolaste muchos pueblos, y has pecado contra tu vida.\n",
    11: " Porque la piedra clamará desde el muro, y la tabla del enmaderado le responderá.\n",
    12: " ¡Ay del que edifica la ciudad con sangre, y del que funda una ciudad con iniquidad!\n",
    13: " ¿No es esto de Jehová de los ejércitos? Los pueblos, pues, trabajarán para el fuego, y las naciones se fatigarán en vano.\n",
    14: " Porque la tierra será llena del conocimiento de la gloria de Jehová, como las aguas cubren el mar.\n",
    15: " ¡Ay del que da de beber a su prójimo! ¡Ay de ti, que le acercas tu hiel, y le embriagas para mirar su desnudez!\n",
    16: " Te has llenado de deshonra más que de honra; bebe tú también, y serás descubierto; el cáliz de la mano derecha de Jehová vendrá hasta ti, y vómito de afrenta sobre tu gloria.\n",
    17: " Porque la rapiña del Líbano caerá sobre ti, y la destrucción de las fieras te quebrantará, a causa de la sangre de los hombres, y del robo de la tierra, de las ciudades y de todos los que en ellas habitaban.\n",
    18: " ¿De qué sirve la escultura que esculpió el que la hizo? ¿la estatua de fundición que enseña mentira, para que haciendo imágenes mudas confíe el hacedor en su obra?\n",
    19: " ¡Ay del que dice al palo: Despiértate; y a la piedra muda: Levántate! ¿Podrá él enseñar? He aquí está cubierto de oro y plata, y no hay espíritu dentro de él.\n",
    20: " Mas Jehová está en su santo templo; calle delante de él toda la tierra. ",
  },
  3: {
    1: " Oración del profeta Habacuc, sobre Sigionot.\n",
    2: " Oh Jehová, he oído tu palabra, y temí. Oh Jehová, aviva tu obra en medio de los tiempos, En medio de los tiempos hazla conocer; En la ira acuérdate de la misericordia.\n",
    3: " Dios vendrá de Temán, Y el Santo desde el monte de Parán. Selah Su gloria cubrió los cielos, Y la tierra se llenó de su alabanza.\n",
    4: " Y el resplandor fue como la luz; Rayos brillantes salían de su mano, Y allí estaba escondido su poder.\n",
    5: " Delante de su rostro iba mortandad, Y a sus pies salían carbones encendidos.\n",
    6: " Se levantó, y midió la tierra; Miró, e hizo temblar las gentes; Los montes antiguos fueron desmenuzados, Los collados antiguos se humillaron. Sus caminos son eternos.\n",
    7: " He visto las tiendas de Cusán en aflicción; Las tiendas de la tierra de Madián temblaron.\n",
    8: " ¿Te airaste, oh Jehová, contra los ríos? ¿Contra los ríos te airaste? ¿Fue tu ira contra el mar Cuando montaste en tus caballos, Y en tus carros de victoria?\n",
    9: " Se descubrió enteramente tu arco; Los juramentos a las tribus fueron palabra segura. Selah Hendiste la tierra con ríos.\n",
    10: " Te vieron y tuvieron temor los montes; Pasó la inundación de las aguas; El abismo dio su voz, A lo alto alzó sus manos.\n",
    11: " El sol y la luna se pararon en su lugar; A la luz de tus saetas anduvieron, Y al resplandor de tu fulgente lanza.\n",
    12: " Con ira hollaste la tierra, Con furor trillaste las naciones.\n",
    13: " Saliste para socorrer a tu pueblo, Para socorrer a tu ungido. Traspasaste la cabeza de la casa del impío, Descubriendo el cimiento hasta la roca. Selah\n",
    14: " Horadaste con sus propios dardos las cabezas de sus guerreros, Que como tempestad acometieron para dispersarme, Cuyo regocijo era como para devorar al pobre encubiertamente.\n",
    15: " Caminaste en el mar con tus caballos, Sobre la mole de las grandes aguas.\n",
    16: " Oí, y se conmovieron mis entrañas; A la voz temblaron mis labios; Pudrición entró en mis huesos, y dentro de mí me estremecí; Si bien estaré quieto en el día de la angustia, Cuando suba al pueblo el que lo invadirá con sus tropas.\n",
    17: " Aunque la higuera no florezca, Ni en las vides haya frutos, Aunque falte el producto del olivo, Y los labrados no den mantenimiento, Y las ovejas sean quitadas de la majada, Y no haya vacas en los corrales;\n",
    18: " Con todo, yo me alegraré en Jehová, Y me gozaré en el Dios de mi salvación.\n",
    19: " Jehová el Señor es mi fortaleza, El cual hace mis pies como de ciervas, Y en mis alturas me hace andar. Al jefe de los cantores, sobre mis instrumentos de cuerdas. ",
  },
};
export default habacuc;
