const juan1 = {
  1: {
    1: " Lo que era desde el principio, lo que hemos oído, lo que hemos visto con nuestros ojos, lo que hemos contemplado, y palparon nuestras manos tocante al Verbo de vida\n",
    2: " (porque la vida fue manifestada, y la hemos visto, y testificamos, y os anunciamos la vida eterna, la cual estaba con el Padre, y se nos manifestó);\n",
    3: " lo que hemos visto y oído, eso os anunciamos, para que también vosotros tengáis comunión con nosotros; y nuestra comunión verdaderamente es con el Padre, y con su Hijo Jesucristo.\n",
    4: " Estas cosas os escribimos, para que vuestro gozo sea cumplido.\n",
    5: " Este es el mensaje que hemos oído de él, y os anunciamos: Dios es luz, y no hay ningunas tinieblas en él.\n",
    6: " Si decimos que tenemos comunión con él, y andamos en tinieblas, mentimos, y no practicamos la verdad;\n",
    7: " pero si andamos en luz, como él está en luz, tenemos comunión unos con otros, y la sangre de Jesucristo su Hijo nos limpia de todo pecado.\n",
    8: " Si decimos que no tenemos pecado, nos engañamos a nosotros mismos, y la verdad no está en nosotros.\n",
    9: " Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad.\n",
    10: " Si decimos que no hemos pecado, le hacemos a él mentiroso, y su palabra no está en nosotros. ",
  },
  2: {
    1: " Hijitos míos, estas cosas os escribo para que no pequéis; y si alguno hubiere pecado, abogado tenemos para con el Padre, a Jesucristo el justo.\n",
    2: " Y él es la propiciación por nuestros pecados; y no solamente por los nuestros, sino también por los de todo el mundo.\n",
    3: " Y en esto sabemos que nosotros le conocemos, si guardamos sus mandamientos.\n",
    4: " El que dice: Yo le conozco, y no guarda sus mandamientos, el tal es mentiroso, y la verdad no está en él;\n",
    5: " pero el que guarda su palabra, en éste verdaderamente el amor de Dios se ha perfeccionado; por esto sabemos que estamos en él.\n",
    6: " El que dice que permanece en él, debe andar como él anduvo.\n",
    7: " Hermanos, no os escribo mandamiento nuevo, sino el mandamiento antiguo que habéis tenido desde el principio; este mandamiento antiguo es la palabra que habéis oído desde el principio.\n",
    8: " Sin embargo, os escribo un mandamiento nuevo, que es verdadero en él y en vosotros, porque las tinieblas van pasando, y la luz verdadera ya alumbra.\n",
    9: " El que dice que está en la luz, y aborrece a su hermano, está todavía en tinieblas.\n",
    10: " El que ama a su hermano, permanece en la luz, y en él no hay tropiezo.\n",
    11: " Pero el que aborrece a su hermano está en tinieblas, y anda en tinieblas, y no sabe a dónde va, porque las tinieblas le han cegado los ojos.\n",
    12: " Os escribo a vosotros, hijitos, porque vuestros pecados os han sido perdonados por su nombre.\n",
    13: " Os escribo a vosotros, padres, porque conocéis al que es desde el principio. Os escribo a vosotros, jóvenes, porque habéis vencido al maligno. Os escribo a vosotros, hijitos, porque habéis conocido al Padre.\n",
    14: " Os he escrito a vosotros, padres, porque habéis conocido al que es desde el principio. Os he escrito a vosotros, jóvenes, porque sois fuertes, y la palabra de Dios permanece en vosotros, y habéis vencido al maligno.\n",
    15: " No améis al mundo, ni las cosas que están en el mundo. Si alguno ama al mundo, el amor del Padre no está en él.\n",
    16: " Porque todo lo que hay en el mundo, los deseos de la carne, los deseos de los ojos, y la vanagloria de la vida, no proviene del Padre, sino del mundo.\n",
    17: " Y el mundo pasa, y sus deseos; pero el que hace la voluntad de Dios permanece para siempre.\n",
    18: " Hijitos, ya es el último tiempo; y según vosotros oísteis que el anticristo viene, así ahora han surgido muchos anticristos; por esto conocemos que es el último tiempo.\n",
    19: " Salieron de nosotros, pero no eran de nosotros; porque si hubiesen sido de nosotros, habrían permanecido con nosotros; pero salieron para que se manifestase que no todos son de nosotros.\n",
    20: " Pero vosotros tenéis la unción del Santo, y conocéis todas las cosas.\n",
    21: " No os he escrito como si ignoraseis la verdad, sino porque la conocéis, y porque ninguna mentira procede de la verdad.\n",
    22: " ¿Quién es el mentiroso, sino el que niega que Jesús es el Cristo? Este es anticristo, el que niega al Padre y al Hijo.\n",
    23: " Todo aquel que niega al Hijo, tampoco tiene al Padre. El que confiesa al Hijo, tiene también al Padre.\n",
    24: " Lo que habéis oído desde el principio, permanezca en vosotros. Si lo que habéis oído desde el principio permanece en vosotros, también vosotros permaneceréis en el Hijo y en el Padre.\n",
    25: " Y esta es la promesa que él nos hizo, la vida eterna.\n",
    26: " Os he escrito esto sobre los que os engañan.\n",
    27: " Pero la unción que vosotros recibisteis de él permanece en vosotros, y no tenéis necesidad de que nadie os enseñe; así como la unción misma os enseña todas las cosas, y es verdadera, y no es mentira, según ella os ha enseñado, permaneced en él.\n",
    28: " Y ahora, hijitos, permaneced en él, para que cuando se manifieste, tengamos confianza, para que en su venida no nos alejemos de él avergonzados.\n",
    29: " Si sabéis que él es justo, sabed también que todo el que hace justicia es nacido de él. ",
  },
  3: {
    1: " Mirad cuál amor nos ha dado el Padre, para que seamos llamados hijos de Dios; por esto el mundo no nos conoce, porque no le conoció a él.\n",
    2: " Amados, ahora somos hijos de Dios, y aún no se ha manifestado lo que hemos de ser; pero sabemos que cuando él se manifieste, seremos semejantes a él, porque le veremos tal como él es.\n",
    3: " Y todo aquel que tiene esta esperanza en él, se purifica a sí mismo, así como él es puro.\n",
    4: " Todo aquel que comete pecado, infringe también la ley; pues el pecado es infracción de la ley.\n",
    5: " Y sabéis que él apareció para quitar nuestros pecados, y no hay pecado en él.\n",
    6: " Todo aquel que permanece en él, no peca; todo aquel que peca, no le ha visto, ni le ha conocido.\n",
    7: " Hijitos, nadie os engañe; el que hace justicia es justo, como él es justo.\n",
    8: " El que practica el pecado es del diablo; porque el diablo peca desde el principio. Para esto apareció el Hijo de Dios, para deshacer las obras del diablo.\n",
    9: " Todo aquel que es nacido de Dios, no practica el pecado, porque la simiente de Dios permanece en él; y no puede pecar, porque es nacido de Dios.\n",
    10: " En esto se manifiestan los hijos de Dios, y los hijos del diablo: todo aquel que no hace justicia, y que no ama a su hermano, no es de Dios.\n",
    11: " Porque este es el mensaje que habéis oído desde el principio: Que nos amemos unos a otros.\n",
    12: " No como Caín, que era del maligno y mató a su hermano. ¿Y por qué causa le mató? Porque sus obras eran malas, y las de su hermano justas.\n",
    13: " Hermanos míos, no os extrañéis si el mundo os aborrece.\n",
    14: " Nosotros sabemos que hemos pasado de muerte a vida, en que amamos a los hermanos. El que no ama a su hermano, permanece en muerte.\n",
    15: " Todo aquel que aborrece a su hermano es homicida; y sabéis que ningún homicida tiene vida eterna permanente en él.\n",
    16: " En esto hemos conocido el amor, en que él puso su vida por nosotros; también nosotros debemos poner nuestras vidas por los hermanos.\n",
    17: " Pero el que tiene bienes de este mundo y ve a su hermano tener necesidad, y cierra contra él su corazón, ¿cómo mora el amor de Dios en él?\n",
    18: " Hijitos míos, no amemos de palabra ni de lengua, sino de hecho y en verdad.\n",
    19: " Y en esto conocemos que somos de la verdad, y aseguraremos nuestros corazones delante de él;\n",
    20: " pues si nuestro corazón nos reprende, mayor que nuestro corazón es Dios, y él sabe todas las cosas.\n",
    21: " Amados, si nuestro corazón no nos reprende, confianza tenemos en Dios;\n",
    22: " y cualquiera cosa que pidiéremos la recibiremos de él, porque guardamos sus mandamientos, y hacemos las cosas que son agradables delante de él.\n",
    23: " Y este es su mandamiento: Que creamos en el nombre de su Hijo Jesucristo, y nos amemos unos a otros como nos lo ha mandado.\n",
    24: " Y el que guarda sus mandamientos, permanece en Dios, y Dios en él. Y en esto sabemos que él permanece en nosotros, por el Espíritu que nos ha dado. ",
  },
  4: {
    1: " Amados, no creáis a todo espíritu, sino probad los espíritus si son de Dios; porque muchos falsos profetas han salido por el mundo.\n",
    2: " En esto conoced el Espíritu de Dios: Todo espíritu que confiesa que Jesucristo ha venido en carne, es de Dios;\n",
    3: " y todo espíritu que no confiesa que Jesucristo ha venido en carne, no es de Dios; y este es el espíritu del anticristo, el cual vosotros habéis oído que viene, y que ahora ya está en el mundo.\n",
    4: " Hijitos, vosotros sois de Dios, y los habéis vencido; porque mayor es el que está en vosotros, que el que está en el mundo.\n",
    5: " Ellos son del mundo; por eso hablan del mundo, y el mundo los oye.\n",
    6: " Nosotros somos de Dios; el que conoce a Dios, nos oye; el que no es de Dios, no nos oye. En esto conocemos el espíritu de verdad y el espíritu de error.\n",
    7: " Amados, amémonos unos a otros; porque el amor es de Dios. Todo aquel que ama, es nacido de Dios, y conoce a Dios.\n",
    8: " El que no ama, no ha conocido a Dios; porque Dios es amor.\n",
    9: " En esto se mostró el amor de Dios para con nosotros, en que Dios envió a su Hijo unigénito al mundo, para que vivamos por él.\n",
    10: " En esto consiste el amor: no en que nosotros hayamos amado a Dios, sino en que él nos amó a nosotros, y envió a su Hijo en propiciación por nuestros pecados.\n",
    11: " Amados, si Dios nos ha amado así, debemos también nosotros amarnos unos a otros.\n",
    12: " Nadie ha visto jamás a Dios. Si nos amamos unos a otros, Dios permanece en nosotros, y su amor se ha perfeccionado en nosotros.\n",
    13: " En esto conocemos que permanecemos en él, y él en nosotros, en que nos ha dado de su Espíritu.\n",
    14: " Y nosotros hemos visto y testificamos que el Padre ha enviado al Hijo, el Salvador del mundo.\n",
    15: " Todo aquel que confiese que Jesús es el Hijo de Dios, Dios permanece en él, y él en Dios.\n",
    16: " Y nosotros hemos conocido y creído el amor que Dios tiene para con nosotros. Dios es amor; y el que permanece en amor, permanece en Dios, y Dios en él.\n",
    17: " En esto se ha perfeccionado el amor en nosotros, para que tengamos confianza en el día del juicio; pues como él es, así somos nosotros en este mundo.\n",
    18: " En el amor no hay temor, sino que el perfecto amor echa fuera el temor; porque el temor lleva en sí castigo. De donde el que teme, no ha sido perfeccionado en el amor.\n",
    19: " Nosotros le amamos a él, porque él nos amó primero.\n",
    20: " Si alguno dice: Yo amo a Dios, y aborrece a su hermano, es mentiroso. Pues el que no ama a su hermano a quien ha visto, ¿cómo puede amar a Dios a quien no ha visto?\n",
    21: " Y nosotros tenemos este mandamiento de él: El que ama a Dios, ame también a su hermano. ",
  },
  5: {
    1: " Todo aquel que cree que Jesús es el Cristo, es nacido de Dios; y todo aquel que ama al que engendró, ama también al que ha sido engendrado por él.\n",
    2: " En esto conocemos que amamos a los hijos de Dios, cuando amamos a Dios, y guardamos sus mandamientos.\n",
    3: " Pues este es el amor a Dios, que guardemos sus mandamientos; y sus mandamientos no son gravosos.\n",
    4: " Porque todo lo que es nacido de Dios vence al mundo; y esta es la victoria que ha vencido al mundo, nuestra fe.\n",
    5: " ¿Quién es el que vence al mundo, sino el que cree que Jesús es el Hijo de Dios?\n",
    6: " Este es Jesucristo, que vino mediante agua y sangre; no mediante agua solamente, sino mediante agua y sangre. Y el Espíritu es el que da testimonio; porque el Espíritu es la verdad.\n",
    7: " Porque tres son los que dan testimonio en el cielo: el Padre, el Verbo y el Espíritu Santo; y estos tres son uno.\n",
    8: " Y tres son los que dan testimonio en la tierra: el Espíritu, el agua y la sangre; y estos tres concuerdan.\n",
    9: " Si recibimos el testimonio de los hombres, mayor es el testimonio de Dios; porque este es el testimonio con que Dios ha testificado acerca de su Hijo.\n",
    10: " El que cree en el Hijo de Dios, tiene el testimonio en sí mismo; el que no cree a Dios, le ha hecho mentiroso, porque no ha creído en el testimonio que Dios ha dado acerca de su Hijo.\n",
    11: " Y este es el testimonio: que Dios nos ha dado vida eterna; y esta vida está en su Hijo.\n",
    12: " El que tiene al Hijo, tiene la vida; el que no tiene al Hijo de Dios no tiene la vida.\n",
    13: " Estas cosas os he escrito a vosotros que creéis en el nombre del Hijo de Dios, para que sepáis que tenéis vida eterna, y para que creáis en el nombre del Hijo de Dios.\n",
    14: " Y esta es la confianza que tenemos en él, que si pedimos alguna cosa conforme a su voluntad, él nos oye.\n",
    15: " Y si sabemos que él nos oye en cualquiera cosa que pidamos, sabemos que tenemos las peticiones que le hayamos hecho.\n",
    16: " Si alguno viere a su hermano cometer pecado que no sea de muerte, pedirá, y Dios le dará vida; esto es para los que cometen pecado que no sea de muerte. Hay pecado de muerte, por el cual yo no digo que se pida.\n",
    17: " Toda injusticia es pecado; pero hay pecado no de muerte.\n",
    18: " Sabemos que todo aquel que ha nacido de Dios, no practica el pecado, pues Aquel que fue engendrado por Dios le guarda, y el maligno no le toca.\n",
    19: " Sabemos que somos de Dios, y el mundo entero está bajo el maligno.\n",
    20: " Pero sabemos que el Hijo de Dios ha venido, y nos ha dado entendimiento para conocer al que es verdadero; y estamos en el verdadero, en su Hijo Jesucristo. Este es el verdadero Dios, y la vida eterna.\n",
    21: " Hijitos, guardaos de los ídolos. Amén. ",
  },
};
export default juan1;
