const pedro1 = {
  1: {
    1: " Pedro, apóstol de Jesucristo, a los expatriados de la dispersión en el Ponto, Galacia, Capadocia, Asia y Bitinia,\n",
    2: " elegidos según la presciencia de Dios Padre en santificación del Espíritu, para obedecer y ser rociados con la sangre de Jesucristo: Gracia y paz os sean multiplicadas.\n",
    3: " Bendito el Dios y Padre de nuestro Señor Jesucristo, que según su grande misericordia nos hizo renacer para una esperanza viva, por la resurrección de Jesucristo de los muertos,\n",
    4: " para una herencia incorruptible, incontaminada e inmarcesible, reservada en los cielos para vosotros,\n",
    5: " que sois guardados por el poder de Dios mediante la fe, para alcanzar la salvación que está preparada para ser manifestada en el tiempo postrero.\n",
    6: " En lo cual vosotros os alegráis, aunque ahora por un poco de tiempo, si es necesario, tengáis que ser afligidos en diversas pruebas,\n",
    7: " para que sometida a prueba vuestra fe, mucho más preciosa que el oro, el cual aunque perecedero se prueba con fuego, sea hallada en alabanza, gloria y honra cuando sea manifestado Jesucristo,\n",
    8: " a quien amáis sin haberle visto, en quien creyendo, aunque ahora no lo veáis, os alegráis con gozo inefable y glorioso;\n",
    9: " obteniendo el fin de vuestra fe, que es la salvación de vuestras almas.\n",
    10: " Los profetas que profetizaron de la gracia destinada a vosotros, inquirieron y diligentemente indagaron acerca de esta salvación,\n",
    11: " escudriñando qué persona y qué tiempo indicaba el Espíritu de Cristo que estaba en ellos, el cual anunciaba de antemano los sufrimientos de Cristo, y las glorias que vendrían tras ellos.\n",
    12: " A éstos se les reveló que no para sí mismos, sino para nosotros, administraban las cosas que ahora os son anunciadas por los que os han predicado el evangelio por el Espíritu Santo enviado del cielo; cosas en las cuales anhelan mirar los ángeles.\n",
    13: " Por tanto, ceñid los lomos de vuestro entendimiento, sed sobrios, y esperad por completo en la gracia que se os traerá cuando Jesucristo sea manifestado;\n",
    14: " como hijos obedientes, no os conforméis a los deseos que antes teníais estando en vuestra ignorancia;\n",
    15: " sino, como aquel que os llamó es santo, sed también vosotros santos en toda vuestra manera de vivir;\n",
    16: " porque escrito está: Sed santos, porque yo soy santo.\n",
    17: " Y si invocáis por Padre a aquel que sin acepción de personas juzga según la obra de cada uno, conducíos en temor todo el tiempo de vuestra peregrinación;\n",
    18: " sabiendo que fuisteis rescatados de vuestra vana manera de vivir, la cual recibisteis de vuestros padres, no con cosas corruptibles, como oro o plata,\n",
    19: " sino con la sangre preciosa de Cristo, como de un cordero sin mancha y sin contaminación,\n",
    20: " ya destinado desde antes de la fundación del mundo, pero manifestado en los postreros tiempos por amor de vosotros,\n",
    21: " y mediante el cual creéis en Dios, quien le resucitó de los muertos y le ha dado gloria, para que vuestra fe y esperanza sean en Dios.\n",
    22: " Habiendo purificado vuestras almas por la obediencia a la verdad, mediante el Espíritu, para el amor fraternal no fingido, amaos unos a otros entrañablemente, de corazón puro;\n",
    23: " siendo renacidos, no de simiente corruptible, sino de incorruptible, por la palabra de Dios que vive y permanece para siempre.\n",
    24: " Porque: Toda carne es como hierba, Y toda la gloria del hombre como flor de la hierba. La hierba se seca, y la flor se cae;\n",
    25: " Mas la palabra del Señor permanece para siempre. Y esta es la palabra que por el evangelio os ha sido anunciada. ",
  },
  2: {
    1: " Desechando, pues, toda malicia, todo engaño, hipocresía, envidias, y todas las detracciones,\n",
    2: " desead, como niños recién nacidos, la leche espiritual no adulterada, para que por ella crezcáis para salvación,\n",
    3: " si es que habéis gustado la benignidad del Señor.\n",
    4: " Acercándoos a él, piedra viva, desechada ciertamente por los hombres, mas para Dios escogida y preciosa,\n",
    5: " vosotros también, como piedras vivas, sed edificados como casa espiritual y sacerdocio santo, para ofrecer sacrificios espirituales aceptables a Dios por medio de Jesucristo.\n",
    6: " Por lo cual también contiene la Escritura: He aquí, pongo en Sion la principal piedra del ángulo, escogida, preciosa; Y el que creyere en él, no será avergonzado.\n",
    7: " Para vosotros, pues, los que creéis, él es precioso; pero para los que no creen, La piedra que los edificadores desecharon, Ha venido a ser la cabeza del ángulo;\n",
    8: " y: Piedra de tropiezo, y roca que hace caer, porque tropiezan en la palabra, siendo desobedientes; a lo cual fueron también destinados.\n",
    9: " Mas vosotros sois linaje escogido, real sacerdocio, nación santa, pueblo adquirido por Dios, para que anunciéis las virtudes de aquel que os llamó de las tinieblas a su luz admirable;\n",
    10: " vosotros que en otro tiempo no erais pueblo, pero que ahora sois pueblo de Dios; que en otro tiempo no habíais alcanzado misericordia, pero ahora habéis alcanzado misericordia.\n",
    11: " Amados, yo os ruego como a extranjeros y peregrinos, que os abstengáis de los deseos carnales que batallan contra el alma,\n",
    12: " manteniendo buena vuestra manera de vivir entre los gentiles; para que en lo que murmuran de vosotros como de malhechores, glorifiquen a Dios en el día de la visitación, al considerar vuestras buenas obras.\n",
    13: " Por causa del Señor someteos a toda institución humana, ya sea al rey, como a superior,\n",
    14: " ya a los gobernadores, como por él enviados para castigo de los malhechores y alabanza de los que hacen bien.\n",
    15: " Porque esta es la voluntad de Dios: que haciendo bien, hagáis callar la ignorancia de los hombres insensatos;\n",
    16: " como libres, pero no como los que tienen la libertad como pretexto para hacer lo malo, sino como siervos de Dios.\n",
    17: " Honrad a todos. Amad a los hermanos. Temed a Dios. Honrad al rey.\n",
    18: " Criados, estad sujetos con todo respeto a vuestros amos; no solamente a los buenos y afables, sino también a los difíciles de soportar.\n",
    19: " Porque esto merece aprobación, si alguno a causa de la conciencia delante de Dios, sufre molestias padeciendo injustamente.\n",
    20: " Pues ¿qué gloria es, si pecando sois abofeteados, y lo soportáis? Mas si haciendo lo bueno sufrís, y lo soportáis, esto ciertamente es aprobado delante de Dios.\n",
    21: " Pues para esto fuisteis llamados; porque también Cristo padeció por nosotros, dejándonos ejemplo, para que sigáis sus pisadas;\n",
    22: " el cual no hizo pecado, ni se halló engaño en su boca;\n",
    23: " quien cuando le maldecían, no respondía con maldición; cuando padecía, no amenazaba, sino encomendaba la causa al que juzga justamente;\n",
    24: " quien llevó él mismo nuestros pecados en su cuerpo sobre el madero, para que nosotros, estando muertos a los pecados, vivamos a la justicia; y por cuya herida fuisteis sanados.\n",
    25: " Porque vosotros erais como ovejas descarriadas, pero ahora habéis vuelto al Pastor y Obispo de vuestras almas. ",
  },
  3: {
    1: " Asimismo vosotras, mujeres, estad sujetas a vuestros maridos; para que también los que no creen a la palabra, sean ganados sin palabra por la conducta de sus esposas,\n",
    2: " considerando vuestra conducta casta y respetuosa.\n",
    3: " Vuestro atavío no sea el externo de peinados ostentosos, de adornos de oro o de vestidos lujosos,\n",
    4: " sino el interno, el del corazón, en el incorruptible ornato de un espíritu afable y apacible, que es de grande estima delante de Dios.\n",
    5: " Porque así también se ataviaban en otro tiempo aquellas santas mujeres que esperaban en Dios, estando sujetas a sus maridos;\n",
    6: " como Sara obedecía a Abraham, llamándole señor; de la cual vosotras habéis venido a ser hijas, si hacéis el bien, sin temer ninguna amenaza.\n",
    7: " Vosotros, maridos, igualmente, vivid con ellas sabiamente, dando honor a la mujer como a vaso más frágil, y como a coherederas de la gracia de la vida, para que vuestras oraciones no tengan estorbo.\n",
    8: " Finalmente, sed todos de un mismo sentir, compasivos, amándoos fraternalmente, misericordiosos, amigables;\n",
    9: " no devolviendo mal por mal, ni maldición por maldición, sino por el contrario, bendiciendo, sabiendo que fuisteis llamados para que heredaseis bendición.\n",
    10: " Porque: El que quiere amar la vida Y ver días buenos, Refrene su lengua de mal, Y sus labios no hablen engaño;\n",
    11: " Apártese del mal, y haga el bien; Busque la paz, y sígala.\n",
    12: " Porque los ojos del Señor están sobre los justos, Y sus oídos atentos a sus oraciones; Pero el rostro del Señor está contra aquellos que hacen el mal.\n",
    13: " ¿Y quién es aquel que os podrá hacer daño, si vosotros seguís el bien?\n",
    14: " Mas también si alguna cosa padecéis por causa de la justicia, bienaventurados sois. Por tanto, no os amedrentéis por temor de ellos, ni os conturbéis,\n",
    15: " sino santificad a Dios el Señor en vuestros corazones, y estad siempre preparados para presentar defensa con mansedumbre y reverencia ante todo el que os demande razón de la esperanza que hay en vosotros;\n",
    16: " teniendo buena conciencia, para que en lo que murmuran de vosotros como de malhechores, sean avergonzados los que calumnian vuestra buena conducta en Cristo.\n",
    17: " Porque mejor es que padezcáis haciendo el bien, si la voluntad de Dios así lo quiere, que haciendo el mal.\n",
    18: " Porque también Cristo padeció una sola vez por los pecados, el justo por los injustos, para llevarnos a Dios, siendo a la verdad muerto en la carne, pero vivificado en espíritu;\n",
    19: " en el cual también fue y predicó a los espíritus encarcelados,\n",
    20: " los que en otro tiempo desobedecieron, cuando una vez esperaba la paciencia de Dios en los días de Noé, mientras se preparaba el arca, en la cual pocas personas, es decir, ocho, fueron salvadas por agua.\n",
    21: " El bautismo que corresponde a esto ahora nos salva (no quitando las inmundicias de la carne, sino como la aspiración de una buena conciencia hacia Dios) por la resurrección de Jesucristo,\n",
    22: " quien habiendo subido al cielo está a la diestra de Dios; y a él están sujetos ángeles, autoridades y potestades. ",
  },
  4: {
    1: " Puesto que Cristo ha padecido por nosotros en la carne, vosotros también armaos del mismo pensamiento; pues quien ha padecido en la carne, terminó con el pecado,\n",
    2: " para no vivir el tiempo que resta en la carne, conforme a las concupiscencias de los hombres, sino conforme a la voluntad de Dios.\n",
    3: " Baste ya el tiempo pasado para haber hecho lo que agrada a los gentiles, andando en lascivias, concupiscencias, embriagueces, orgías, disipación y abominables idolatrías.\n",
    4: " A éstos les parece cosa extraña que vosotros no corráis con ellos en el mismo desenfreno de disolución, y os ultrajan;\n",
    5: " pero ellos darán cuenta al que está preparado para juzgar a los vivos y a los muertos.\n",
    6: " Porque por esto también ha sido predicado el evangelio a los muertos, para que sean juzgados en carne según los hombres, pero vivan en espíritu según Dios.\n",
    7: " Mas el fin de todas las cosas se acerca; sed, pues, sobrios, y velad en oración.\n",
    8: " Y ante todo, tened entre vosotros ferviente amor; porque el amor cubrirá multitud de pecados.\n",
    9: " Hospedaos los unos a los otros sin murmuraciones.\n",
    10: " Cada uno según el don que ha recibido, minístrelo a los otros, como buenos administradores de la multiforme gracia de Dios.\n",
    11: " Si alguno habla, hable conforme a las palabras de Dios; si alguno ministra, ministre conforme al poder que Dios da, para que en todo sea Dios glorificado por Jesucristo, a quien pertenecen la gloria y el imperio por los siglos de los siglos. Amén.\n",
    12: " Amados, no os sorprendáis del fuego de prueba que os ha sobrevenido, como si alguna cosa extraña os aconteciese,\n",
    13: " sino gozaos por cuanto sois participantes de los padecimientos de Cristo, para que también en la revelación de su gloria os gocéis con gran alegría.\n",
    14: " Si sois vituperados por el nombre de Cristo, sois bienaventurados, porque el glorioso Espíritu de Dios reposa sobre vosotros. Ciertamente, de parte de ellos, él es blasfemado, pero por vosotros es glorificado.\n",
    15: " Así que, ninguno de vosotros padezca como homicida, o ladrón, o malhechor, o por entremeterse en lo ajeno;\n",
    16: " pero si alguno padece como cristiano, no se avergüence, sino glorifique a Dios por ello.\n",
    17: " Porque es tiempo de que el juicio comience por la casa de Dios; y si primero comienza por nosotros, ¿cuál será el fin de aquellos que no obedecen al evangelio de Dios?\n",
    18: " Y: Si el justo con dificultad se salva, ¿En dónde aparecerá el impío y el pecador?\n",
    19: " De modo que los que padecen según la voluntad de Dios, encomienden sus almas al fiel Creador, y hagan el bien. ",
  },
  5: {
    1: " Ruego a los ancianos que están entre vosotros, yo anciano también con ellos, y testigo de los padecimientos de Cristo, que soy también participante de la gloria que será revelada:\n",
    2: " Apacentad la grey de Dios que está entre vosotros, cuidando de ella, no por fuerza, sino voluntariamente; no por ganancia deshonesta, sino con ánimo pronto;\n",
    3: " no como teniendo señorío sobre los que están a vuestro cuidado, sino siendo ejemplos de la grey.\n",
    4: " Y cuando aparezca el Príncipe de los pastores, vosotros recibiréis la corona incorruptible de gloria.\n",
    5: " Igualmente, jóvenes, estad sujetos a los ancianos; y todos, sumisos unos a otros, revestíos de humildad; porque: Dios resiste a los soberbios, Y da gracia a los humildes.\n",
    6: " Humillaos, pues, bajo la poderosa mano de Dios, para que él os exalte cuando fuere tiempo;\n",
    7: " echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.\n",
    8: " Sed sobrios, y velad; porque vuestro adversario el diablo, como león rugiente, anda alrededor buscando a quien devorar;\n",
    9: " al cual resistid firmes en la fe, sabiendo que los mismos padecimientos se van cumpliendo en vuestros hermanos en todo el mundo.\n",
    10: " Mas el Dios de toda gracia, que nos llamó a su gloria eterna en Jesucristo, después que hayáis padecido un poco de tiempo, él mismo os perfeccione, afirme, fortalezca y establezca.\n",
    11: " A él sea la gloria y el imperio por los siglos de los siglos. Amén.\n",
    12: " Por conducto de Silvano, a quien tengo por hermano fiel, os he escrito brevemente, amonestándoos, y testificando que ésta es la verdadera gracia de Dios, en la cual estáis.\n",
    13: " La iglesia que está en Babilonia, elegida juntamente con vosotros, y Marcos mi hijo, os saludan.\n",
    14: " Saludaos unos a otros con ósculo de amor. Paz sea con todos vosotros los que estáis en Jesucristo. Amén. ",
  },
};
export default pedro1;
