const proverbios = {
  1: {
    1: " Los proverbios de Salomón, hijo de David, rey de Israel.\n",
    2: " Para entender sabiduría y doctrina, Para conocer razones prudentes,\n",
    3: " Para recibir el consejo de prudencia, Justicia, juicio y equidad;\n",
    4: " Para dar sagacidad a los simples, Y a los jóvenes inteligencia y cordura.\n",
    5: " Oirá el sabio, y aumentará el saber, Y el entendido adquirirá consejo,\n",
    6: " Para entender proverbio y declaración, Palabras de sabios, y sus dichos profundos.\n",
    7: " El principio de la sabiduría es el temor de Jehová; Los insensatos desprecian la sabiduría y la enseñanza. Amonestaciones de la Sabiduría\n",
    8: " Oye, hijo mío, la instrucción de tu padre, Y no desprecies la dirección de tu madre;\n",
    9: " Porque adorno de gracia serán a tu cabeza, Y collares a tu cuello.\n",
    10: " Hijo mío, si los pecadores te quisieren engañar, No consientas.\n",
    11: " Si dijeren: Ven con nosotros; Pongamos asechanzas para derramar sangre, Acechemos sin motivo al inocente;\n",
    12: " Los tragaremos vivos como el Seol, Y enteros, como los que caen en un abismo;\n",
    13: " Hallaremos riquezas de toda clase, Llenaremos nuestras casas de despojos;\n",
    14: " Echa tu suerte entre nosotros; Tengamos todos una bolsa.\n",
    15: " Hijo mío, no andes en camino con ellos. Aparta tu pie de sus veredas,\n",
    16: " Porque sus pies corren hacia el mal, Y van presurosos a derramar sangre.\n",
    17: " Porque en vano se tenderá la red Ante los ojos de toda ave;\n",
    18: " Pero ellos a su propia sangre ponen asechanzas, Y a sus almas tienden lazo.\n",
    19: " Tales son las sendas de todo el que es dado a la codicia, La cual quita la vida de sus poseedores.\n",
    20: " La sabiduría clama en las calles, Alza su voz en las plazas;\n",
    21: " Clama en los principales lugares de reunión; En las entradas de las puertas de la ciudad dice sus razones.\n",
    22: " ¿Hasta cuándo, oh simples, amaréis la simpleza, Y los burladores desearán el burlar, Y los insensatos aborrecerán la ciencia?\n",
    23: " Volveos a mi reprensión; He aquí yo derramaré mi espíritu sobre vosotros, Y os haré saber mis palabras.\n",
    24: " Por cuanto llamé, y no quisisteis oír, Extendí mi mano, y no hubo quien atendiese,\n",
    25: " Sino que desechasteis todo consejo mío Y mi reprensión no quisisteis,\n",
    26: " También yo me reiré en vuestra calamidad, Y me burlaré cuando os viniere lo que teméis;\n",
    27: " Cuando viniere como una destrucción lo que teméis, Y vuestra calamidad llegare como un torbellino; Cuando sobre vosotros viniere tribulación y angustia.\n",
    28: " Entonces me llamarán, y no responderé; Me buscarán de mañana, y no me hallarán.\n",
    29: " Por cuanto aborrecieron la sabiduría, Y no escogieron el temor de Jehová,\n",
    30: " Ni quisieron mi consejo, Y menospreciaron toda reprensión mía,\n",
    31: " Comerán del fruto de su camino, Y serán hastiados de sus propios consejos.\n",
    32: " Porque el desvío de los ignorantes los matará, Y la prosperidad de los necios los echará a perder;\n",
    33: " Mas el que me oyere, habitará confiadamente Y vivirá tranquilo, sin temor del mal. ",
  },
  2: {
    1: " Hijo mío, si recibieres mis palabras, Y mis mandamientos guardares dentro de ti,\n",
    2: " Haciendo estar atento tu oído a la sabiduría; Si inclinares tu corazón a la prudencia,\n",
    3: " Si clamares a la inteligencia, Y a la prudencia dieres tu voz;\n",
    4: " Si como a la plata la buscares, Y la escudriñares como a tesoros,\n",
    5: " Entonces entenderás el temor de Jehová, Y hallarás el conocimiento de Dios.\n",
    6: " Porque Jehová da la sabiduría, Y de su boca viene el conocimiento y la inteligencia.\n",
    7: " El provee de sana sabiduría a los rectos; Es escudo a los que caminan rectamente.\n",
    8: " Es el que guarda las veredas del juicio, Y preserva el camino de sus santos.\n",
    9: " Entonces entenderás justicia, juicio Y equidad, y todo buen camino.\n",
    10: " Cuando la sabiduría entrare en tu corazón, Y la ciencia fuere grata a tu alma,\n",
    11: " La discreción te guardará; Te preservará la inteligencia,\n",
    12: " Para librarte del mal camino, De los hombres que hablan perversidades,\n",
    13: " Que dejan los caminos derechos, Para andar por sendas tenebrosas;\n",
    14: " Que se alegran haciendo el mal, Que se huelgan en las perversidades del vicio;\n",
    15: " Cuyas veredas son torcidas, Y torcidos sus caminos.\n",
    16: " Serás librado de la mujer extraña, De la ajena que halaga con sus palabras,\n",
    17: " La cual abandona al compañero de su juventud, Y se olvida del pacto de su Dios.\n",
    18: " Por lo cual su casa está inclinada a la muerte, Y sus veredas hacia los muertos;\n",
    19: " Todos los que a ella se lleguen, no volverán, Ni seguirán otra vez los senderos de la vida.\n",
    20: " Así andarás por el camino de los buenos, Y seguirás las veredas de los justos;\n",
    21: " Porque los rectos habitarán la tierra, Y los perfectos permanecerán en ella,\n",
    22: " Mas los impíos serán cortados de la tierra, Y los prevaricadores serán de ella desarraigados. ",
  },
  3: {
    1: " Hijo mío, no te olvides de mi ley, Y tu corazón guarde mis mandamientos;\n",
    2: " Porque largura de días y años de vida Y paz te aumentarán.\n",
    3: " Nunca se aparten de ti la misericordia y la verdad; Atalas a tu cuello, Escríbelas en la tabla de tu corazón;\n",
    4: " Y hallarás gracia y buena opinión Ante los ojos de Dios y de los hombres.\n",
    5: " Fíate de Jehová de todo tu corazón, Y no te apoyes en tu propia prudencia.\n",
    6: " Reconócelo en todos tus caminos, Y él enderezará tus veredas.\n",
    7: " No seas sabio en tu propia opinión; Teme a Jehová, y apártate del mal;\n",
    8: " Porque será medicina a tu cuerpo, Y refrigerio para tus huesos.\n",
    9: " Honra a Jehová con tus bienes, Y con las primicias de todos tus frutos;\n",
    10: " Y serán llenos tus graneros con abundancia, Y tus lagares rebosarán de mosto.\n",
    11: " No menosprecies, hijo mío, el castigo de Jehová, Ni te fatigues de su corrección;\n",
    12: " Porque Jehová al que ama castiga, Como el padre al hijo a quien quiere.\n",
    13: " Bienaventurado el hombre que halla la sabiduría, Y que obtiene la inteligencia;\n",
    14: " Porque su ganancia es mejor que la ganancia de la plata, Y sus frutos más que el oro fino.\n",
    15: " Más preciosa es que las piedras preciosas; Y todo lo que puedes desear, no se puede comparar a ella.\n",
    16: " Largura de días está en su mano derecha; En su izquierda, riquezas y honra.\n",
    17: " Sus caminos son caminos deleitosos, Y todas sus veredas paz.\n",
    18: " Ella es árbol de vida a los que de ella echan mano, Y bienaventurados son los que la retienen.\n",
    19: " Jehová con sabiduría fundó la tierra; Afirmó los cielos con inteligencia.\n",
    20: " Con su ciencia los abismos fueron divididos, Y destilan rocío los cielos.\n",
    21: " Hijo mío, no se aparten estas cosas de tus ojos; Guarda la ley y el consejo,\n",
    22: " Y serán vida a tu alma, Y gracia a tu cuello.\n",
    23: " Entonces andarás por tu camino confiadamente, Y tu pie no tropezará.\n",
    24: " Cuando te acuestes, no tendrás temor, Sino que te acostarás, y tu sueño será grato.\n",
    25: " No tendrás temor de pavor repentino, Ni de la ruina de los impíos cuando viniere,\n",
    26: " Porque Jehová será tu confianza, Y él preservará tu pie de quedar preso.\n",
    27: " No te niegues a hacer el bien a quien es debido, Cuando tuvieres poder para hacerlo.\n",
    28: " No digas a tu prójimo: Anda, y vuelve, Y mañana te daré, Cuando tienes contigo qué darle.\n",
    29: " No intentes mal contra tu prójimo Que habita confiado junto a ti.\n",
    30: " No tengas pleito con nadie sin razón, Si no te han hecho agravio.\n",
    31: " No envidies al hombre injusto, Ni escojas ninguno de sus caminos.\n",
    32: " Porque Jehová abomina al perverso; Mas su comunión íntima es con los justos.\n",
    33: " La maldición de Jehová está en la casa del impío, Pero bendecirá la morada de los justos.\n",
    34: " Ciertamente él escarnecerá a los escarnecedores, Y a los humildes dará gracia.\n",
    35: " Los sabios heredarán honra, Mas los necios llevarán ignominia. ",
  },
  4: {
    1: " Oíd, hijos, la enseñanza de un padre, Y estad atentos, para que conozcáis cordura.\n",
    2: " Porque os doy buena enseñanza; No desamparéis mi ley.\n",
    3: " Porque yo también fui hijo de mi padre, Delicado y único delante de mi madre.\n",
    4: " Y él me enseñaba, y me decía: Retenga tu corazón mis razones, Guarda mis mandamientos, y vivirás.\n",
    5: " Adquiere sabiduría, adquiere inteligencia; No te olvides ni te apartes de las razones de mi boca;\n",
    6: " No la dejes, y ella te guardará; Amala, y te conservará.\n",
    7: " Sabiduría ante todo; adquiere sabiduría; Y sobre todas tus posesiones adquiere inteligencia.\n",
    8: " Engrandécela, y ella te engrandecerá; Ella te honrará, cuando tú la hayas abrazado.\n",
    9: " Adorno de gracia dará a tu cabeza; Corona de hermosura te entregará.\n",
    10: " Oye, hijo mío, y recibe mis razones, Y se te multiplicarán años de vida.\n",
    11: " Por el camino de la sabiduría te he encaminado, Y por veredas derechas te he hecho andar.\n",
    12: " Cuando anduvieres, no se estrecharán tus pasos, Y si corrieres, no tropezarás.\n",
    13: " Retén el consejo, no lo dejes; Guárdalo, porque eso es tu vida.\n",
    14: " No entres por la vereda de los impíos, Ni vayas por el camino de los malos.\n",
    15: " Déjala, no pases por ella; Apártate de ella, pasa.\n",
    16: " Porque no duermen ellos si no han hecho mal, Y pierden el sueño si no han hecho caer a alguno.\n",
    17: " Porque comen pan de maldad, y beben vino de robos;\n",
    18: " Mas la senda de los justos es como la luz de la aurora, Que va en aumento hasta que el día es perfecto.\n",
    19: " El camino de los impíos es como la oscuridad; No saben en qué tropiezan.\n",
    20: " Hijo mío, está atento a mis palabras; Inclina tu oído a mis razones.\n",
    21: " No se aparten de tus ojos; Guárdalas en medio de tu corazón;\n",
    22: " Porque son vida a los que las hallan, Y medicina a todo su cuerpo.\n",
    23: " Sobre toda cosa guardada, guarda tu corazón; Porque de él mana la vida.\n",
    24: " Aparta de ti la perversidad de la boca, Y aleja de ti la iniquidad de los labios.\n",
    25: " Tus ojos miren lo recto, Y diríjanse tus párpados hacia lo que tienes delante.\n",
    26: " Examina la senda de tus pies, Y todos tus caminos sean rectos.\n",
    27: " No te desvíes a la derecha ni a la izquierda; Aparta tu pie del mal. ",
  },
  5: {
    1: " Hijo mío, está atento a mi sabiduría, Y a mi inteligencia inclina tu oído,\n",
    2: " Para que guardes consejo, Y tus labios conserven la ciencia.\n",
    3: " Porque los labios de la mujer extraña destilan miel, Y su paladar es más blando que el aceite;\n",
    4: " Mas su fin es amargo como el ajenjo, Agudo como espada de dos filos.\n",
    5: " Sus pies descienden a la muerte; Sus pasos conducen al Seol.\n",
    6: " Sus caminos son inestables; no los conocerás, Si no considerares el camino de vida.\n",
    7: " Ahora pues, hijos, oídme, Y no os apartéis de las razones de mi boca.\n",
    8: " Aleja de ella tu camino, Y no te acerques a la puerta de su casa;\n",
    9: " Para que no des a los extraños tu honor, Y tus años al cruel;\n",
    10: " No sea que extraños se sacien de tu fuerza, Y tus trabajos estén en casa del extraño;\n",
    11: " Y gimas al final, Cuando se consuma tu carne y tu cuerpo,\n",
    12: " Y digas: ¡Cómo aborrecí el consejo, Y mi corazón menospreció la reprensión;\n",
    13: " No oí la voz de los que me instruían, Y a los que me enseñaban no incliné mi oído!\n",
    14: " Casi en todo mal he estado, En medio de la sociedad y de la congregación.\n",
    15: " Bebe el agua de tu misma cisterna, Y los raudales de tu propio pozo.\n",
    16: " ¿Se derramarán tus fuentes por las calles, Y tus corrientes de aguas por las plazas?\n",
    17: " Sean para ti solo, Y no para los extraños contigo.\n",
    18: " Sea bendito tu manantial, Y alégrate con la mujer de tu juventud,\n",
    19: " Como cierva amada y graciosa gacela. Sus caricias te satisfagan en todo tiempo, Y en su amor recréate siempre.\n",
    20: " ¿Y por qué, hijo mío, andarás ciego con la mujer ajena, Y abrazarás el seno de la extraña?\n",
    21: " Porque los caminos del hombre están ante los ojos de Jehová, Y él considera todas sus veredas.\n",
    22: " Prenderán al impío sus propias iniquidades, Y retenido será con las cuerdas de su pecado.\n",
    23: " El morirá por falta de corrección, Y errará por lo inmenso de su locura. ",
  },
  6: {
    1: " Hijo mío, si salieres fiador por tu amigo, Si has empeñado tu palabra a un extraño,\n",
    2: " Te has enlazado con las palabras de tu boca, Y has quedado preso en los dichos de tus labios.\n",
    3: " Haz esto ahora, hijo mío, y líbrate, Ya que has caído en la mano de tu prójimo; Vé, humíllate, y asegúrate de tu amigo.\n",
    4: " No des sueño a tus ojos, Ni a tus párpados adormecimiento;\n",
    5: " Escápate como gacela de la mano del cazador, Y como ave de la mano del que arma lazos.\n",
    6: " Ve a la hormiga, oh perezoso, Mira sus caminos, y sé sabio;\n",
    7: " La cual no teniendo capitán, Ni gobernador, ni señor,\n",
    8: " Prepara en el verano su comida, Y recoge en el tiempo de la siega su mantenimiento.\n",
    9: " Perezoso, ¿hasta cuándo has de dormir? ¿Cuándo te levantarás de tu sueño?\n",
    10: " Un poco de sueño, un poco de dormitar, Y cruzar por un poco las manos para reposo;\n",
    11: " Así vendrá tu necesidad como caminante, Y tu pobreza como hombre armado.\n",
    12: " El hombre malo, el hombre depravado, Es el que anda en perversidad de boca;\n",
    13: " Que guiña los ojos, que habla con los pies, Que hace señas con los dedos.\n",
    14: " Perversidades hay en su corazón; anda pensando el mal en todo tiempo; Siembra las discordias.\n",
    15: " Por tanto, su calamidad vendrá de repente; Súbitamente será quebrantado, y no habrá remedio.\n",
    16: " Seis cosas aborrece Jehová, Y aun siete abomina su alma:\n",
    17: " Los ojos altivos, la lengua mentirosa, Las manos derramadoras de sangre inocente,\n",
    18: " El corazón que maquina pensamientos inicuos, Los pies presurosos para correr al mal,\n",
    19: "El testigo falso que habla mentiras, Y el que siembra discordia entre hermanos.\n",
    20: " Guarda, hijo mío, el mandamiento de tu padre, Y no dejes la enseñanza de tu madre;\n",
    21: " Atalos siempre en tu corazón, Enlázalos a tu cuello.\n",
    22: " Te guiarán cuando andes; cuando duermas te guardarán; Hablarán contigo cuando despiertes.\n",
    23: " Porque el mandamiento es lámpara, y la enseñanza es luz, Y camino de vida las reprensiones que te instruyen,\n",
    24: " Para que te guarden de la mala mujer, De la blandura de la lengua de la mujer extraña.\n",
    25: " No codicies su hermosura en tu corazón, Ni ella te prenda con sus ojos;\n",
    26: " Porque a causa de la mujer ramera el hombre es reducido a un bocado de pan; Y la mujer caza la preciosa alma del varón.\n",
    27: " ¿Tomará el hombre fuego en su seno Sin que sus vestidos ardan?\n",
    28: " ¿Andará el hombre sobre brasas Sin que sus pies se quemen?\n",
    29: " Así es el que se llega a la mujer de su prójimo; No quedará impune ninguno que la tocare.\n",
    30: " No tienen en poco al ladrón si hurta Para saciar su apetito cuando tiene hambre;\n",
    31: " Pero si es sorprendido, pagará siete veces; Entregará todo el haber de su casa.\n",
    32: " Mas el que comete adulterio es falto de entendimiento; Corrompe su alma el que tal hace.\n",
    33: " Heridas y vergüenza hallará, Y su afrenta nunca será borrada.\n",
    34: " Porque los celos son el furor del hombre, Y no perdonará en el día de la venganza.\n",
    35: " No aceptará ningún rescate, Ni querrá perdonar, aunque multipliques los dones. ",
  },
  7: {
    1: " Hijo mío, guarda mis razones, Y atesora contigo mis mandamientos.\n",
    2: " Guarda mis mandamientos y vivirás, Y mi ley como las niñas de tus ojos.\n",
    3: " Lígalos a tus dedos; Escríbelos en la tabla de tu corazón.\n",
    4: " Dí a la sabiduría: Tú eres mi hermana, Y a la inteligencia llama parienta;\n",
    5: " Para que te guarden de la mujer ajena, Y de la extraña que ablanda sus palabras.\n",
    6: " Porque mirando yo por la ventana de mi casa, Por mi celosía,\n",
    7: " Vi entre los simples, Consideré entre los jóvenes, A un joven falto de entendimiento,\n",
    8: " El cual pasaba por la calle, junto a la esquina, E iba camino a la casa de ella,\n",
    9: " A la tarde del día, cuando ya oscurecía, En la oscuridad y tinieblas de la noche.\n",
    10: " Cuando he aquí, una mujer le sale al encuentro, Con atavío de ramera y astuta de corazón.\n",
    11: " Alborotadora y rencillosa, Sus pies no pueden estar en casa;\n",
    12: " Unas veces está en la calle, otras veces en las plazas, Acechando por todas las esquinas.\n",
    13: " Se asió de él, y le besó. Con semblante descarado le dijo:\n",
    14: " Sacrificios de paz había prometido, Hoy he pagado mis votos;\n",
    15: " Por tanto, he salido a encontrarte, Buscando diligentemente tu rostro, y te he hallado.\n",
    16: " He adornado mi cama con colchas Recamadas con cordoncillo de Egipto;\n",
    17: " He perfumado mi cámara Con mirra, áloes y canela.\n",
    18: " Ven, embriaguémonos de amores hasta la mañana; Alegrémonos en amores.\n",
    19: " Porque el marido no está en casa; Se ha ido a un largo viaje.\n",
    20: " La bolsa de dinero llevó en su mano; El día señalado volverá a su casa.\n",
    21: " Lo rindió con la suavidad de sus muchas palabras, Le obligó con la zalamería de sus labios.\n",
    22: " Al punto se marchó tras ella, Como va el buey al degolladero, Y como el necio a las prisiones para ser castigado;\n",
    23: " Como el ave que se apresura a la red, Y no sabe que es contra su vida, Hasta que la saeta traspasa su corazón.\n",
    24: " Ahora pues, hijos, oídme, Y estad atentos a las razones de mi boca.\n",
    25: " No se aparte tu corazón a sus caminos; No yerres en sus veredas.\n",
    26: " Porque a muchos ha hecho caer heridos, Y aun los más fuertes han sido muertos por ella.\n",
    27: " Camino al Seol es su casa, Que conduce a las cámaras de la muerte. ",
  },
  8: {
    1: " ¿No clama la sabiduría, Y da su voz la inteligencia?\n",
    2: " En las alturas junto al camino, A las encrucijadas de las veredas se para;\n",
    3: " En el lugar de las puertas, a la entrada de la ciudad, A la entrada de las puertas da voces:\n",
    4: " Oh hombres, a vosotros clamo; Dirijo mi voz a los hijos de los hombres.\n",
    5: " Entended, oh simples, discreción; Y vosotros, necios, entrad en cordura.\n",
    6: " Oíd, porque hablaré cosas excelentes, Y abriré mis labios para cosas rectas.\n",
    7: " Porque mi boca hablará verdad, Y la impiedad abominan mis labios.\n",
    8: " Justas son todas las razones de mi boca; No hay en ellas cosa perversa ni torcida.\n",
    9: " Todas ellas son rectas al que entiende, Y razonables a los que han hallado sabiduría.\n",
    10: " Recibid mi enseñanza, y no plata; Y ciencia antes que el oro escogido.\n",
    11: " Porque mejor es la sabiduría que las piedras preciosas; Y todo cuanto se puede desear, no es de compararse con ella.\n",
    12: " Yo, la sabiduría, habito con la cordura, Y hallo la ciencia de los consejos.\n",
    13: " El temor de Jehová es aborrecer el mal; La soberbia y la arrogancia, el mal camino, Y la boca perversa, aborrezco.\n",
    14: " Conmigo está el consejo y el buen juicio; Yo soy la inteligencia; mío es el poder.\n",
    15: " Por mí reinan los reyes, Y los príncipes determinan justicia.\n",
    16: " Por mí dominan los príncipes, Y todos los gobernadores juzgan la tierra.\n",
    17: " Yo amo a los que me aman, Y me hallan los que temprano me buscan.\n",
    18: " Las riquezas y la honra están conmigo; Riquezas duraderas, y justicia.\n",
    19: " Mejor es mi fruto que el oro, y que el oro refinado; Y mi rédito mejor que la plata escogida.\n",
    20: " Por vereda de justicia guiaré, Por en medio de sendas de juicio,\n",
    21: " Para hacer que los que me aman tengan su heredad, Y que yo llene sus tesoros.\n",
    22: " Jehová me poseía en el principio, Ya de antiguo, antes de sus obras.\n",
    23: " Eternamente tuve el principado, desde el principio, Antes de la tierra.\n",
    24: " Antes de los abismos fui engendrada; Antes que fuesen las fuentes de las muchas aguas.\n",
    25: " Antes que los montes fuesen formados, Antes de los collados, ya había sido yo engendrada;\n",
    26: " No había aún hecho la tierra, ni los campos, Ni el principio del polvo del mundo.\n",
    27: " Cuando formaba los cielos, allí estaba yo; Cuando trazaba el círculo sobre la faz del abismo;\n",
    28: " Cuando afirmaba los cielos arriba, Cuando afirmaba las fuentes del abismo;\n",
    29: " Cuando ponía al mar su estatuto, Para que las aguas no traspasasen su mandamiento; Cuando establecía los fundamentos de la tierra,\n",
    30: " Con él estaba yo ordenándolo todo, Y era su delicia de día en día, Teniendo solaz delante de él en todo tiempo.\n",
    31: " Me regocijo en la parte habitable de su tierra; Y mis delicias son con los hijos de los hombres.\n",
    32: " Ahora, pues, hijos, oídme, Y bienaventurados los que guardan mis caminos.\n",
    33: " Atended el consejo, y sed sabios, Y no lo menospreciéis.\n",
    34: " Bienaventurado el hombre que me escucha, Velando a mis puertas cada día, Aguardando a los postes de mis puertas.\n",
    35: " Porque el que me halle, hallará la vida, Y alcanzará el favor de Jehová.\n",
    36: " Mas el que peca contra mí, defrauda su alma; Todos los que me aborrecen aman la muerte. ",
  },
  9: {
    1: " La sabiduría edificó su casa, Labró sus siete columnas.\n",
    2: " Mató sus víctimas, mezcló su vino, Y puso su mesa.\n",
    3: " Envió sus criadas; Sobre lo más alto de la ciudad clamó.\n",
    4: " Dice a cualquier simple: Ven acá. A los faltos de cordura dice:\n",
    5: " Venid, comed mi pan, Y bebed del vino que yo he mezclado.\n",
    6: " Dejad las simplezas, y vivid, Y andad por el camino de la inteligencia.\n",
    7: " El que corrige al escarnecedor, se acarrea afrenta; El que reprende al impío, se atrae mancha.\n",
    8: " No reprendas al escarnecedor, para que no te aborrezca; Corrige al sabio, y te amará.\n",
    9: " Da al sabio, y será más sabio; Enseña al justo, y aumentará su saber.\n",
    10: " El temor de Jehová es el principio de la sabiduría, Y el conocimiento del Santísimo es la inteligencia.\n",
    11: " Porque por mí se aumentarán tus días, Y años de vida se te añadirán.\n",
    12: " Si fueres sabio, para ti lo serás; Y si fueres escarnecedor, pagarás tú solo.\n",
    13: " La mujer insensata es alborotadora; Es simple e ignorante.\n",
    14: " Se sienta en una silla a la puerta de su casa, En los lugares altos de la ciudad,\n",
    15: " Para llamar a los que pasan por el camino, Que van por sus caminos derechos.\n",
    16: " Dice a cualquier simple: Ven acá. A los faltos de cordura dijo:\n",
    17: " Las aguas hurtadas son dulces, Y el pan comido en oculto es sabroso.\n",
    18: " Y no saben que allí están los muertos; Que sus convidados están en lo profundo del Seol. ",
  },
  10: {
    1: " Los proverbios de Salomón. El hijo sabio alegra al padre, Pero el hijo necio es tristeza de su madre.\n",
    2: " Los tesoros de maldad no serán de provecho; Mas la justicia libra de muerte.\n",
    3: " Jehová no dejará padecer hambre al justo; Mas la iniquidad lanzará a los impíos.\n",
    4: " La mano negligente empobrece; Mas la mano de los diligentes enriquece.\n",
    5: " El que recoge en el verano es hombre entendido; El que duerme en el tiempo de la siega es hijo que avergüenza.\n",
    6: " Hay bendiciones sobre la cabeza del justo; Pero violencia cubrirá la boca de los impíos.\n",
    7: " La memoria del justo será bendita; Mas el nombre de los impíos se pudrirá.\n",
    8: " El sabio de corazón recibirá los mandamientos; Mas el necio de labios caerá.\n",
    9: " El que camina en integridad anda confiado; Mas el que pervierte sus caminos será quebrantado.\n",
    10: " El que guiña el ojo acarrea tristeza; Y el necio de labios será castigado.\n",
    11: " Manantial de vida es la boca del justo; Pero violencia cubrirá la boca de los impíos.\n",
    12: " El odio despierta rencillas; Pero el amor cubrirá todas las faltas.\n",
    13: " En los labios del prudente se halla sabiduría; Mas la vara es para las espaldas del falto de cordura.\n",
    14: " Los sabios guardan la sabiduría; Mas la boca del necio es calamidad cercana.\n",
    15: " Las riquezas del rico son su ciudad fortificada; Y el desmayo de los pobres es su pobreza.\n",
    16: " La obra del justo es para vida; Mas el fruto del impío es para pecado.\n",
    17: " Camino a la vida es guardar la instrucción; Pero quien desecha la reprensión, yerra.\n",
    18: " El que encubre el odio es de labios mentirosos; Y el que propaga calumnia es necio.\n",
    19: " En las muchas palabras no falta pecado; Mas el que refrena sus labios es prudente.\n",
    20: " Plata escogida es la lengua del justo; Mas el corazón de los impíos es como nada.\n",
    21: " Los labios del justo apacientan a muchos, Mas los necios mueren por falta de entendimiento.\n",
    22: " La bendición de Jehová es la que enriquece, Y no añade tristeza con ella.\n",
    23: " El hacer maldad es como una diversión al insensato; Mas la sabiduría recrea al hombre de entendimiento.\n",
    24: " Lo que el impío teme, eso le vendrá; Pero a los justos les será dado lo que desean.\n",
    25: " Como pasa el torbellino, así el malo no permanece; Mas el justo permanece para siempre.\n",
    26: " Como el vinagre a los dientes, y como el humo a los ojos, Así es el perezoso a los que lo envían.\n",
    27: " El temor de Jehová aumentará los días; Mas los años de los impíos serán acortados.\n",
    28: " La esperanza de los justos es alegría; Mas la esperanza de los impíos perecerá.\n",
    29: " El camino de Jehová es fortaleza al perfecto; Pero es destrucción a los que hacen maldad.\n",
    30: " El justo no será removido jamás; Pero los impíos no habitarán la tierra.\n",
    31: " La boca del justo producirá sabiduría; Mas la lengua perversa será cortada.\n",
    32: " Los labios del justo saben hablar lo que agrada; Mas la boca de los impíos habla perversidades. ",
  },
  11: {
    1: " El peso falso es abominación a Jehová; Mas la pesa cabal le agrada.\n",
    2: " Cuando viene la soberbia, viene también la deshonra; Mas con los humildes está la sabiduría.\n",
    3: " La integridad de los rectos los encaminará; Pero destruirá a los pecadores la perversidad de ellos.\n",
    4: " No aprovecharán las riquezas en el día de la ira; Mas la justicia librará de muerte.\n",
    5: " La justicia del perfecto enderezará su camino; Mas el impío por su impiedad caerá.\n",
    6: " La justicia de los rectos los librará; Mas los pecadores serán atrapados en su pecado.\n",
    7: " Cuando muere el hombre impío, perece su esperanza; Y la expectación de los malos perecerá.\n",
    8: " El justo es librado de la tribulación; Mas el impío entra en lugar suyo.\n",
    9: " El hipócrita con la boca daña a su prójimo; Mas los justos son librados con la sabiduría.\n",
    10: " En el bien de los justos la ciudad se alegra; Mas cuando los impíos perecen hay fiesta.\n",
    11: " Por la bendición de los rectos la ciudad será engrandecida; Mas por la boca de los impíos será trastornada.\n",
    12: " El que carece de entendimiento menosprecia a su prójimo; Mas el hombre prudente calla.\n",
    13: " El que anda en chismes descubre el secreto; Mas el de espíritu fiel lo guarda todo.\n",
    14: " Donde no hay dirección sabia, caerá el pueblo; Mas en la multitud de consejeros hay seguridad.\n",
    15: " Con ansiedad será afligido el que sale por fiador de un extraño; Mas el que aborreciere las fianzas vivirá seguro.\n",
    16: " La mujer agraciada tendrá honra, Y los fuertes tendrán riquezas.\n",
    17: " A su alma hace bien el hombre misericordioso; Mas el cruel se atormenta a sí mismo.\n",
    18: " El impío hace obra falsa; Mas el que siembra justicia tendrá galardón firme.\n",
    19: " Como la justicia conduce a la vida, Así el que sigue el mal lo hace para su muerte.\n",
    20: " Abominación son a Jehová los perversos de corazón; Mas los perfectos de camino le son agradables.\n",
    21: " Tarde o temprano, el malo será castigado; Mas la descendencia de los justos será librada.\n",
    22: " Como zarcillo de oro en el hocico de un cerdo Es la mujer hermosa y apartada de razón.\n",
    23: " El deseo de los justos es solamente el bien; Mas la esperanza de los impíos es el enojo.\n",
    24: " Hay quienes reparten, y les es añadido más; Y hay quienes retienen más de lo que es justo, pero vienen a pobreza.\n",
    25: " El alma generosa será prosperada; Y el que saciare, él también será saciado.\n",
    26: " Al que acapara el grano, el pueblo lo maldecirá; Pero bendición será sobre la cabeza del que lo vende.\n",
    27: " El que procura el bien buscará favor; Mas al que busca el mal, éste le vendrá.\n",
    28: " El que confía en sus riquezas caerá; Mas los justos reverdecerán como ramas.\n",
    29: " El que turba su casa heredará viento; Y el necio será siervo del sabio de corazón.\n",
    30: " El fruto del justo es árbol de vida; Y el que gana almas es sabio.\n",
    31: " Ciertamente el justo será recompensado en la tierra; ¡Cuánto más el impío y el pecador! ",
  },
  12: {
    1: " El que ama la instrucción ama la sabiduría; Mas el que aborrece la reprensión es ignorante.\n",
    2: " El bueno alcanzará favor de Jehová; Mas él condenará al hombre de malos pensamientos.\n",
    3: " El hombre no se afirmará por medio de la impiedad; Mas la raíz de los justos no será removida.\n",
    4: " La mujer virtuosa es corona de su marido; Mas la mala, como carcoma en sus huesos.\n",
    5: " Los pensamientos de los justos son rectitud; Mas los consejos de los impíos, engaño.\n",
    6: " Las palabras de los impíos son asechanzas para derramar sangre; Mas la boca de los rectos los librará.\n",
    7: " Dios trastornará a los impíos, y no serán más; Pero la casa de los justos permanecerá firme.\n",
    8: " Según su sabiduría es alabado el hombre; Mas el perverso de corazón será menospreciado.\n",
    9: " Más vale el despreciado que tiene servidores, Que el que se jacta, y carece de pan.\n",
    10: " El justo cuida de la vida de su bestia; Mas el corazón de los impíos es cruel.\n",
    11: " El que labra su tierra se saciará de pan; Mas el que sigue a los vagabundos es falto de entendimiento.\n",
    12: " Codicia el impío la red de los malvados; Mas la raíz de los justos dará fruto.\n",
    13: " El impío es enredado en la prevaricación de sus labios; Mas el justo saldrá de la tribulación.\n",
    14: " El hombre será saciado de bien del fruto de su boca; Y le será pagado según la obra de sus manos.\n",
    15: " El camino del necio es derecho en su opinión; Mas el que obedece al consejo es sabio.\n",
    16: " El necio al punto da a conocer su ira; Mas el que no hace caso de la injuria es prudente.\n",
    17: " El que habla verdad declara justicia; Mas el testigo mentiroso, engaño.\n",
    18: " Hay hombres cuyas palabras son como golpes de espada; Mas la lengua de los sabios es medicina.\n",
    19: " El labio veraz permanecerá para siempre; Mas la lengua mentirosa sólo por un momento.\n",
    20: " Engaño hay en el corazón de los que piensan el mal; Pero alegría en el de los que piensan el bien.\n",
    21: " Ninguna adversidad acontecerá al justo; Mas los impíos serán colmados de males.\n",
    22: " Los labios mentirosos son abominación a Jehová; Pero los que hacen verdad son su contentamiento.\n",
    23: " El hombre cuerdo encubre su saber; Mas el corazón de los necios publica la necedad.\n",
    24: " La mano de los diligentes señoreará; Mas la negligencia será tributaria.\n",
    25: " La congoja en el corazón del hombre lo abate; Mas la buena palabra lo alegra.\n",
    26: " El justo sirve de guía a su prójimo; Mas el camino de los impíos les hace errar.\n",
    27: " El indolente ni aun asará lo que ha cazado; Pero haber precioso del hombre es la diligencia.\n",
    28: " En el camino de la justicia está la vida; Y en sus caminos no hay muerte. ",
  },
  13: {
    1: " El hijo sabio recibe el consejo del padre; Mas el burlador no escucha las reprensiones.\n",
    2: " Del fruto de su boca el hombre comerá el bien; Mas el alma de los prevaricadores hallará el mal.\n",
    3: " El que guarda su boca guarda su alma; Mas el que mucho abre sus labios tendrá calamidad.\n",
    4: " El alma del perezoso desea, y nada alcanza; Mas el alma de los diligentes será prosperada.\n",
    5: " El justo aborrece la palabra de mentira; Mas el impío se hace odioso e infame.\n",
    6: " La justicia guarda al de perfecto camino; Mas la impiedad trastornará al pecador.\n",
    7: " Hay quienes pretenden ser ricos, y no tienen nada; Y hay quienes pretenden ser pobres, y tienen muchas riquezas.\n",
    8: " El rescate de la vida del hombre está en sus riquezas; Pero el pobre no oye censuras.\n",
    9: " La luz de los justos se alegrará; Mas se apagará la lámpara de los impíos.\n",
    10: " Ciertamente la soberbia concebirá contienda; Mas con los avisados está la sabiduría.\n",
    11: " Las riquezas de vanidad disminuirán; Pero el que recoge con mano laboriosa las aumenta.\n",
    12: " La esperanza que se demora es tormento del corazón; Pero árbol de vida es el deseo cumplido.\n",
    13: " El que menosprecia el precepto perecerá por ello; Mas el que teme el mandamiento será recompensado.\n",
    14: " La ley del sabio es manantial de vida Para apartarse de los lazos de la muerte.\n",
    15: " El buen entendimiento da gracia; Mas el camino de los transgresores es duro.\n",
    16: " Todo hombre prudente procede con sabiduría; Mas el necio manifestará necedad.\n",
    17: " El mal mensajero acarrea desgracia; Mas el mensajero fiel acarrea salud.\n",
    18: " Pobreza y vergüenza tendrá el que menosprecia el consejo; Mas el que guarda la corrección recibirá honra.\n",
    19: " El deseo cumplido regocija el alma; Pero apartarse del mal es abominación a los necios.\n",
    20: " El que anda con sabios, sabio será; Mas el que se junta con necios será quebrantado.\n",
    21: " El mal perseguirá a los pecadores, Mas los justos serán premiados con el bien.\n",
    22: " El bueno dejará herederos a los hijos de sus hijos; Pero la riqueza del pecador está guardada para el justo.\n",
    23: " En el barbecho de los pobres hay mucho pan; Mas se pierde por falta de juicio.\n",
    24: " El que detiene el castigo, a su hijo aborrece; Mas el que lo ama, desde temprano lo corrige.\n",
    25: " El justo come hasta saciar su alma; Mas el vientre de los impíos tendrá necesidad. ",
  },
  14: {
    1: " La mujer sabia edifica su casa; Mas la necia con sus manos la derriba.\n",
    2: " El que camina en su rectitud teme a Jehová; Mas el de caminos pervertidos lo menosprecia.\n",
    3: " En la boca del necio está la vara de la soberbia; Mas los labios de los sabios los guardarán.\n",
    4: " Sin bueyes el granero está vacío; Mas por la fuerza del buey hay abundancia de pan.\n",
    5: " El testigo verdadero no mentirá; Mas el testigo falso hablará mentiras.\n",
    6: " Busca el escarnecedor la sabiduría y no la halla; Mas al hombre entendido la sabiduría le es fácil.\n",
    7: " Vete de delante del hombre necio, Porque en él no hallarás labios de ciencia.\n",
    8: " La ciencia del prudente está en entender su camino; Mas la indiscreción de los necios es engaño.\n",
    9: " Los necios se mofan del pecado; Mas entre los rectos hay buena voluntad.\n",
    10: " El corazón conoce la amargura de su alma; Y extraño no se entremeterá en su alegría.\n",
    11: " La casa de los impíos será asolada; Pero florecerá la tienda de los rectos.\n",
    12: " Hay camino que al hombre le parece derecho; Pero su fin es camino de muerte.\n",
    13: " Aun en la risa tendrá dolor el corazón; Y el término de la alegría es congoja.\n",
    14: " De sus caminos será hastiado el necio de corazón; Pero el hombre de bien estará contento del suyo.\n",
    15: " El simple todo lo cree; Mas el avisado mira bien sus pasos.\n",
    16: " El sabio teme y se aparta del mal; Mas el insensato se muestra insolente y confiado.\n",
    17: " El que fácilmente se enoja hará locuras; Y el hombre perverso será aborrecido.\n",
    18: " Los simples heredarán necedad; Mas los prudentes se coronarán de sabiduría.\n",
    19: " Los malos se inclinarán delante de los buenos, Y los impíos a las puertas del justo.\n",
    20: " El pobre es odioso aun a su amigo; Pero muchos son los que aman al rico.\n",
    21: " Peca el que menosprecia a su prójimo; Mas el que tiene misericordia de los pobres es bienaventurado.\n",
    22: " ¿No yerran los que piensan el mal? Misericordia y verdad alcanzarán los que piensan el bien.\n",
    23: " En toda labor hay fruto; Mas las vanas palabras de los labios empobrecen.\n",
    24: " Las riquezas de los sabios son su corona; Pero la insensatez de los necios es infatuación.\n",
    25: " El testigo verdadero libra las almas; Mas el engañoso hablará mentiras.\n",
    26: " En el temor de Jehová está la fuerte confianza; Y esperanza tendrán sus hijos.\n",
    27: " El temor de Jehová es manantial de vida Para apartarse de los lazos de la muerte.\n",
    28: " En la multitud del pueblo está la gloria del rey; Y en la falta de pueblo la debilidad del príncipe.\n",
    29: " El que tarda en airarse es grande de entendimiento; Mas el que es impaciente de espíritu enaltece la necedad.\n",
    30: " El corazón apacible es vida de la carne; Mas la envidia es carcoma de los huesos.\n",
    31: " El que oprime al pobre afrenta a su Hacedor; Mas el que tiene misericordia del pobre, lo honra.\n",
    32: " Por su maldad será lanzado el impío; Mas el justo en su muerte tiene esperanza.\n",
    33: " En el corazón del prudente reposa la sabiduría; Pero no es conocida en medio de los necios.\n",
    34: " La justicia engrandece a la nación; Mas el pecado es afrenta de las naciones.\n",
    35: " La benevolencia del rey es para con el servidor entendido; Mas su enojo contra el que lo avergüenza. ",
  },
  15: {
    1: " La blanda respuesta quita la ira; Mas la palabra áspera hace subir el furor.\n",
    2: " La lengua de los sabios adornará la sabiduría; Mas la boca de los necios hablará sandeces.\n",
    3: " Los ojos de Jehová están en todo lugar, Mirando a los malos y a los buenos.\n",
    4: " La lengua apacible es árbol de vida; Mas la perversidad de ella es quebrantamiento de espíritu.\n",
    5: " El necio menosprecia el consejo de su padre; Mas el que guarda la corrección vendrá a ser prudente.\n",
    6: " En la casa del justo hay gran provisión; Pero turbación en las ganancias del impío.\n",
    7: " La boca de los sabios esparce sabiduría; No así el corazón de los necios.\n",
    8: " El sacrificio de los impíos es abominación a Jehová; Mas la oración de los rectos es su gozo.\n",
    9: " Abominación es a Jehová el camino del impío; Mas él ama al que sigue justicia.\n",
    10: " La reconvención es molesta al que deja el camino; Y el que aborrece la corrección morirá.\n",
    11: " El Seol y el Abadón están delante de Jehová; ¡Cuánto más los corazones de los hombres!\n",
    12: " El escarnecedor no ama al que le reprende, Ni se junta con los sabios.\n",
    13: " El corazón alegre hermosea el rostro; Mas por el dolor del corazón el espíritu se abate.\n",
    14: " El corazón entendido busca la sabiduría; Mas la boca de los necios se alimenta de necedades.\n",
    15: " Todos los días del afligido son difíciles; Mas el de corazón contento tiene un banquete continuo.\n",
    16: " Mejor es lo poco con el temor de Jehová, Que el gran tesoro donde hay turbación.\n",
    17: " Mejor es la comida de legumbres donde hay amor, Que de buey engordado donde hay odio.\n",
    18: " El hombre iracundo promueve contiendas; Mas el que tarda en airarse apacigua la rencilla.\n",
    19: " El camino del perezoso es como seto de espinos; Mas la vereda de los rectos, como una calzada.\n",
    20: " El hijo sabio alegra al padre; Mas el hombre necio menosprecia a su madre.\n",
    21: " La necedad es alegría al falto de entendimiento; Mas el hombre entendido endereza sus pasos.\n",
    22: " Los pensamientos son frustrados donde no hay consejo; Mas en la multitud de consejeros se afirman.\n",
    23: " El hombre se alegra con la respuesta de su boca; Y la palabra a su tiempo, ¡cuán buena es!\n",
    24: " El camino de la vida es hacia arriba al entendido, Para apartarse del Seol abajo.\n",
    25: " Jehová asolará la casa de los soberbios; Pero afirmará la heredad de la viuda.\n",
    26: " Abominación son a Jehová los pensamientos del malo; Mas las expresiones de los limpios son limpias.\n",
    27: " Alborota su casa el codicioso; Mas el que aborrece el soborno vivirá.\n",
    28: " El corazón del justo piensa para responder; Mas la boca de los impíos derrama malas cosas.\n",
    29: " Jehová está lejos de los impíos; Pero él oye la oración de los justos.\n",
    30: " La luz de los ojos alegra el corazón, Y la buena nueva conforta los huesos.\n",
    31: " El oído que escucha las amonestaciones de la vida, Entre los sabios morará.\n",
    32: " El que tiene en poco la disciplina menosprecia su alma; Mas el que escucha la corrección tiene entendimiento.\n",
    33: " El temor de Jehová es enseñanza de sabiduría; Y a la honra precede la humildad. ",
  },
  16: {
    1: " Del hombre son las disposiciones del corazón; Mas de Jehová es la respuesta de la lengua.\n",
    2: " Todos los caminos del hombre son limpios en su propia opinión; Pero Jehová pesa los espíritus.\n",
    3: " Encomienda a Jehová tus obras, Y tus pensamientos serán afirmados.\n",
    4: " Todas las cosas ha hecho Jehová para sí mismo, Y aun al impío para el día malo.\n",
    5: " Abominación es a Jehová todo altivo de corazón; Ciertamente no quedará impune.\n",
    6: " Con misericordia y verdad se corrige el pecado, Y con el temor de Jehová los hombres se apartan del mal.\n",
    7: " Cuando los caminos del hombre son agradables a Jehová, Aun a sus enemigos hace estar en paz con él.\n",
    8: " Mejor es lo poco con justicia Que la muchedumbre de frutos sin derecho.\n",
    9: " El corazón del hombre piensa su camino; Mas Jehová endereza sus pasos.\n",
    10: " Oráculo hay en los labios del rey; En juicio no prevaricará su boca.\n",
    11: " Peso y balanzas justas son de Jehová; Obra suya son todas las pesas de la bolsa.\n",
    12: " Abominación es a los reyes hacer impiedad, Porque con justicia será afirmado el trono.\n",
    13: " Los labios justos son el contentamiento de los reyes, Y éstos aman al que habla lo recto.\n",
    14: " La ira del rey es mensajero de muerte; Mas el hombre sabio la evitará.\n",
    15: " En la alegría del rostro del rey está la vida, Y su benevolencia es como nube de lluvia tardía.\n",
    16: " Mejor es adquirir sabiduría que oro preciado; Y adquirir inteligencia vale más que la plata.\n",
    17: " El camino de los rectos se aparta del mal; Su vida guarda el que guarda su camino.\n",
    18: " Antes del quebrantamiento es la soberbia, Y antes de la caída la altivez de espíritu.\n",
    19: " Mejor es humillar el espíritu con los humildes Que repartir despojos con los soberbios.\n",
    20: " El entendido en la palabra hallará el bien, Y el que confía en Jehová es bienaventurado.\n",
    21: " El sabio de corazón es llamado prudente, Y la dulzura de labios aumenta el saber.\n",
    22: " Manantial de vida es el entendimiento al que lo posee; Mas la erudición de los necios es necedad.\n",
    23: " El corazón del sabio hace prudente su boca, Y añade gracia a sus labios.\n",
    24: " Panal de miel son los dichos suaves; Suavidad al alma y medicina para los huesos.\n",
    25: " Hay camino que parece derecho al hombre, Pero su fin es camino de muerte.\n",
    26: " El alma del que trabaja, trabaja para sí, Porque su boca le estimula.\n",
    27: " El hombre perverso cava en busca del mal, Y en sus labios hay como llama de fuego.\n",
    28: " El hombre perverso levanta contienda, Y el chismoso aparta a los mejores amigos.\n",
    29: " El hombre malo lisonjea a su prójimo, Y le hace andar por camino no bueno.\n",
    30: " Cierra sus ojos para pensar perversidades; Mueve sus labios, efectúa el mal.\n",
    31: " Corona de honra es la vejez Que se halla en el camino de justicia.\n",
    32: " Mejor es el que tarda en airarse que el fuerte; Y el que se enseñorea de su espíritu, que el que toma una ciudad.\n",
    33: " La suerte se echa en el regazo; Mas de Jehová es la decisión de ella. ",
  },
  17: {
    1: " Mejor es un bocado seco, y en paz, Que casa de contiendas llena de provisiones.\n",
    2: " El siervo prudente se enseñoreará del hijo que deshonra, Y con los hermanos compartirá la herencia.\n",
    3: " El crisol para la plata, y la hornaza para el oro; Pero Jehová prueba los corazones.\n",
    4: " El malo está atento al labio inicuo; Y el mentiroso escucha la lengua detractora.\n",
    5: " El que escarnece al pobre afrenta a su Hacedor; Y el que se alegra de la calamidad no quedará sin castigo.\n",
    6: " Corona de los viejos son los nietos, Y la honra de los hijos, sus padres.\n",
    7: " No conviene al necio la altilocuencia; ¡Cuánto menos al príncipe el labio mentiroso!\n",
    8: " Piedra preciosa es el soborno para el que lo practica; Adondequiera que se vuelve, halla prosperidad.\n",
    9: " El que cubre la falta busca amistad; Mas el que la divulga, aparta al amigo.\n",
    10: " La reprensión aprovecha al entendido, Más que cien azotes al necio.\n",
    11: " El rebelde no busca sino el mal, Y mensajero cruel será enviado contra él.\n",
    12: " Mejor es encontrarse con una osa a la cual han robado sus cachorros, Que con un fatuo en su necedad.\n",
    13: " El que da mal por bien, No se apartará el mal de su casa.\n",
    14: " El que comienza la discordia es como quien suelta las aguas; Deja, pues, la contienda, antes que se enrede.\n",
    15: " El que justifica al impío, y el que condena al justo, Ambos son igualmente abominación a Jehová.\n",
    16: " ¿De qué sirve el precio en la mano del necio para comprar sabiduría, No teniendo entendimiento?\n",
    17: " En todo tiempo ama el amigo, Y es como un hermano en tiempo de angustia.\n",
    18: " El hombre falto de entendimiento presta fianzas, Y sale por fiador en presencia de su amigo.\n",
    19: " El que ama la disputa, ama la transgresión; Y el que abre demasiado la puerta busca su ruina.\n",
    20: " El perverso de corazón nunca hallará el bien, Y el que revuelve con su lengua caerá en el mal.\n",
    21: " El que engendra al insensato, para su tristeza lo engendra; Y el padre del necio no se alegrará.\n",
    22: " El corazón alegre constituye buen remedio; Mas el espíritu triste seca los huesos.\n",
    23: " El impío toma soborno del seno Para pervertir las sendas de la justicia.\n",
    24: " En el rostro del entendido aparece la sabiduría; Mas los ojos del necio vagan hasta el extremo de la tierra.\n",
    25: " El hijo necio es pesadumbre de su padre, Y amargura a la que lo dio a luz.\n",
    26: " Ciertamente no es bueno condenar al justo, Ni herir a los nobles que hacen lo recto.\n",
    27: " El que ahorra sus palabras tiene sabiduría; De espíritu prudente es el hombre entendido.\n",
    28: " Aun el necio, cuando calla, es contado por sabio; El que cierra sus labios es entendido. ",
  },
  18: {
    1: " Su deseo busca el que se desvía, Y se entremete en todo negocio.\n",
    2: " No toma placer el necio en la inteligencia, Sino en que su corazón se descubra.\n",
    3: " Cuando viene el impío, viene también el menosprecio, Y con el deshonrador la afrenta.\n",
    4: " Aguas profundas son las palabras de la boca del hombre; Y arroyo que rebosa, la fuente de la sabiduría.\n",
    5: " Tener respeto a la persona del impío, Para pervertir el derecho del justo, no es bueno.\n",
    6: " Los labios del necio traen contienda; Y su boca los azotes llama.\n",
    7: " La boca del necio es quebrantamiento para sí, Y sus labios son lazos para su alma.\n",
    8: " Las palabras del chismoso son como bocados suaves, Y penetran hasta las entrañas.\n",
    9: " También el que es negligente en su trabajo Es hermano del hombre disipador.\n",
    10: " Torre fuerte es el nombre de Jehová; A él correrá el justo, y será levantado.\n",
    11: " Las riquezas del rico son su ciudad fortificada, Y como un muro alto en su imaginación.\n",
    12: " Antes del quebrantamiento se eleva el corazón del hombre, Y antes de la honra es el abatimiento.\n",
    13: " Al que responde palabra antes de oír, Le es fatuidad y oprobio.\n",
    14: " El ánimo del hombre soportará su enfermedad; Mas ¿quién soportará al ánimo angustiado?\n",
    15: " El corazón del entendido adquiere sabiduría; Y el oído de los sabios busca la ciencia.\n",
    16: " La dádiva del hombre le ensancha el camino Y le lleva delante de los grandes.\n",
    17: " Justo parece el primero que aboga por su causa; Pero viene su adversario, y le descubre.\n",
    18: " La suerte pone fin a los pleitos, Y decide entre los poderosos.\n",
    19: " El hermano ofendido es más tenaz que una ciudad fuerte, Y las contiendas de los hermanos son como cerrojos de alcázar.\n",
    20: " Del fruto de la boca del hombre se llenará su vientre; Se saciará del producto de sus labios.\n",
    21: " La muerte y la vida están en poder de la lengua, Y el que la ama comerá de sus frutos.\n",
    22: " El que halla esposa halla el bien, Y alcanza la benevolencia de Jehová.\n",
    23: " El pobre habla con ruegos, Mas el rico responde durezas.\n",
    24: " El hombre que tiene amigos ha de mostrarse amigo; Y amigo hay más unido que un hermano. ",
  },
  19: {
    1: " Mejor es el pobre que camina en integridad, Que el de perversos labios y fatuo.\n",
    2: " El alma sin ciencia no es buena, Y aquel que se apresura con los pies, peca.\n",
    3: " La insensatez del hombre tuerce su camino, Y luego contra Jehová se irrita su corazón.\n",
    4: " Las riquezas traen muchos amigos; Mas el pobre es apartado de su amigo.\n",
    5: " El testigo falso no quedará sin castigo, Y el que habla mentiras no escapará.\n",
    6: " Muchos buscan el favor del generoso, Y cada uno es amigo del hombre que da.\n",
    7: " Todos los hermanos del pobre le aborrecen; ¡Cuánto más sus amigos se alejarán de él! Buscará la palabra, y no la hallará.\n",
    8: " El que posee entendimiento ama su alma; El que guarda la inteligencia hallará el bien.\n",
    9: " El testigo falso no quedará sin castigo, Y el que habla mentiras perecerá.\n",
    10: " No conviene al necio el deleite; ¡Cuánto menos al siervo ser señor de los príncipes!\n",
    11: " La cordura del hombre detiene su furor, Y su honra es pasar por alto la ofensa.\n",
    12: " Como rugido de cachorro de león es la ira del rey, Y su favor como el rocío sobre la hierba.\n",
    13: " Dolor es para su padre el hijo necio, Y gotera continua las contiendas de la mujer.\n",
    14: " La casa y las riquezas son herencia de los padres; Mas de Jehová la mujer prudente.\n",
    15: " La pereza hace caer en profundo sueño, Y el alma negligente padecerá hambre.\n",
    16: " El que guarda el mandamiento guarda su alma; Mas el que menosprecia sus caminos morirá.\n",
    17: " A Jehová presta el que da al pobre, Y el bien que ha hecho, se lo volverá a pagar.\n",
    18: " Castiga a tu hijo en tanto que hay esperanza; Mas no se apresure tu alma para destruirlo.\n",
    19: " El de grande ira llevará la pena; Y si usa de violencias, añadirá nuevos males.\n",
    20: " Escucha el consejo, y recibe la corrección, Para que seas sabio en tu vejez.\n",
    21: " Muchos pensamientos hay en el corazón del hombre; Mas el consejo de Jehová permanecerá.\n",
    22: " Contentamiento es a los hombres hacer misericordia; Pero mejor es el pobre que el mentiroso.\n",
    23: " El temor de Jehová es para vida, Y con él vivirá lleno de reposo el hombre; No será visitado de mal.\n",
    24: " El perezoso mete su mano en el plato, Y ni aun a su boca la llevará.\n",
    25: " Hiere al escarnecedor, y el simple se hará avisado; Y corrigiendo al entendido, entenderá ciencia.\n",
    26: " El que roba a su padre y ahuyenta a su madre, Es hijo que causa vergüenza y acarrea oprobio.\n",
    27: " Cesa, hijo mío, de oír las enseñanzas Que te hacen divagar de las razones de sabiduría.\n",
    28: " El testigo perverso se burlará del juicio, Y la boca de los impíos encubrirá la iniquidad.\n",
    29: " Preparados están juicios para los escarnecedores, Y azotes para las espaldas de los necios. ",
  },
  20: {
    1: " El vino es escarnecedor, la sidra alborotadora, Y cualquiera que por ellos yerra no es sabio.\n",
    2: " Como rugido de cachorro de león es el terror del rey; El que lo enfurece peca contra sí mismo.\n",
    3: " Honra es del hombre dejar la contienda; Mas todo insensato se envolverá en ella.\n",
    4: " El perezoso no ara a causa del invierno; Pedirá, pues, en la siega, y no hallará.\n",
    5: " Como aguas profundas es el consejo en el corazón del hombre; Mas el hombre entendido lo alcanzará.\n",
    6: " Muchos hombres proclaman cada uno su propia bondad, Pero hombre de verdad, ¿quién lo hallará?\n",
    7: " Camina en su integridad el justo; Sus hijos son dichosos después de él.\n",
    8: " El rey que se sienta en el trono de juicio, Con su mirar disipa todo mal.\n",
    9: " ¿Quién podrá decir: Yo he limpiado mi corazón, Limpio estoy de mi pecado?\n",
    10: " Pesa falsa y medida falsa, Ambas cosas son abominación a Jehová.\n",
    11: " Aun el muchacho es conocido por sus hechos, Si su conducta fuere limpia y recta.\n",
    12: " El oído que oye, y el ojo que ve, Ambas cosas igualmente ha hecho Jehová.\n",
    13: " No ames el sueño, para que no te empobrezcas; Abre tus ojos, y te saciarás de pan.\n",
    14: " El que compra dice: Malo es, malo es; Mas cuando se aparta, se alaba.\n",
    15: " Hay oro y multitud de piedras preciosas; Mas los labios prudentes son joya preciosa.\n",
    16: " Quítale su ropa al que salió por fiador del extraño, Y toma prenda del que sale fiador por los extraños.\n",
    17: " Sabroso es al hombre el pan de mentira; Pero después su boca será llena de cascajo.\n",
    18: " Los pensamientos con el consejo se ordenan; Y con dirección sabia se hace la guerra.\n",
    19: " El que anda en chismes descubre el secreto; No te entremetas, pues, con el suelto de lengua.\n",
    20: " Al que maldice a su padre o a su madre, Se le apagará su lámpara en oscuridad tenebrosa.\n",
    21: " Los bienes que se adquieren de prisa al principio, No serán al final bendecidos.\n",
    22: " No digas: Yo me vengaré; Espera a Jehová, y él te salvará.\n",
    23: " Abominación son a Jehová las pesas falsas, Y la balanza falsa no es buena.\n",
    24: " De Jehová son los pasos del hombre; ¿Cómo, pues, entenderá el hombre su camino?\n",
    25: " Lazo es al hombre hacer apresuradamente voto de consagración, Y después de hacerlo, reflexionar.\n",
    26: " El rey sabio avienta a los impíos, Y sobre ellos hace rodar la rueda.\n",
    27: " Lámpara de Jehová es el espíritu del hombre, La cual escudriña lo más profundo del corazón.\n",
    28: " Misericordia y verdad guardan al rey, Y con clemencia se sustenta su trono.\n",
    29: " La gloria de los jóvenes es su fuerza, Y la hermosura de los ancianos es su vejez.\n",
    30: " Los azotes que hieren son medicina para el malo, Y el castigo purifica el corazón. ",
  },
  21: {
    1: " Como los repartimientos de las aguas, Así está el corazón del rey en la mano de Jehová; A todo lo que quiere lo inclina.\n",
    2: " Todo camino del hombre es recto en su propia opinión; Pero Jehová pesa los corazones.\n",
    3: " Hacer justicia y juicio es a Jehová Más agradable que sacrificio.\n",
    4: " Altivez de ojos, y orgullo de corazón, Y pensamiento de impíos, son pecado.\n",
    5: " Los pensamientos del diligente ciertamente tienden a la abundancia; Mas todo el que se apresura alocadamente, de cierto va a la pobreza.\n",
    6: " Amontonar tesoros con lengua mentirosa Es aliento fugaz de aquellos que buscan la muerte.\n",
    7: " La rapiña de los impíos los destruirá, Por cuanto no quisieron hacer juicio.\n",
    8: " El camino del hombre perverso es torcido y extraño; Mas los hechos del limpio son rectos.\n",
    9: " Mejor es vivir en un rincón del terrado Que con mujer rencillosa en casa espaciosa.\n",
    10: " El alma del impío desea el mal; Su prójimo no halla favor en sus ojos.\n",
    11: " Cuando el escarnecedor es castigado, el simple se hace sabio; Y cuando se le amonesta al sabio, aprende ciencia.\n",
    12: " Considera el justo la casa del impío, Cómo los impíos son trastornados por el mal.\n",
    13: " El que cierra su oído al clamor del pobre, También él clamará, y no será oído.\n",
    14: " La dádiva en secreto calma el furor, Y el don en el seno, la fuerte ira.\n",
    15: " Alegría es para el justo el hacer juicio; Mas destrucción a los que hacen iniquidad.\n",
    16: " El hombre que se aparta del camino de la sabiduría Vendrá a parar en la compañía de los muertos.\n",
    17: " Hombre necesitado será el que ama el deleite, Y el que ama el vino y los ungüentos no se enriquecerá.\n",
    18: " Rescate del justo es el impío, Y por los rectos, el prevaricador.\n",
    19: " Mejor es morar en tierra desierta Que con la mujer rencillosa e iracunda.\n",
    20: " Tesoro precioso y aceite hay en la casa del sabio; Mas el hombre insensato todo lo disipa.\n",
    21: " El que sigue la justicia y la misericordia Hallará la vida, la justicia y la honra.\n",
    22: " Tomó el sabio la ciudad de los fuertes, Y derribó la fuerza en que ella confiaba.\n",
    23: " El que guarda su boca y su lengua, Su alma guarda de angustias.\n",
    24: " Escarnecedor es el nombre del soberbio y presuntuoso Que obra en la insolencia de su presunción.\n",
    25: " El deseo del perezoso le mata, Porque sus manos no quieren trabajar.\n",
    26: " Hay quien todo el día codicia; Pero el justo da, y no detiene su mano.\n",
    27: " El sacrificio de los impíos es abominación; ¡Cuánto más ofreciéndolo con maldad!\n",
    28: " El testigo mentiroso perecerá; Mas el hombre que oye, permanecerá en su dicho.\n",
    29: " El hombre impío endurece su rostro; Mas el recto ordena sus caminos.\n",
    30: " No hay sabiduría, ni inteligencia, Ni consejo, contra Jehová.\n",
    31: " El caballo se alista para el día de la batalla; Mas Jehová es el que da la victoria. ",
  },
  22: {
    1: " De más estima es el buen nombre que las muchas riquezas, Y la buena fama más que la plata y el oro.\n",
    2: " El rico y el pobre se encuentran; A ambos los hizo Jehová.\n",
    3: " El avisado ve el mal y se esconde; Mas los simples pasan y reciben el daño.\n",
    4: " Riquezas, honra y vida Son la remuneración de la humildad y del temor de Jehová.\n",
    5: " Espinos y lazos hay en el camino del perverso; El que guarda su alma se alejará de ellos.\n",
    6: " Instruye al niño en su camino, Y aun cuando fuere viejo no se apartará de él.\n",
    7: " El rico se enseñorea de los pobres, Y el que toma prestado es siervo del que presta.\n",
    8: " El que sembrare iniquidad, iniquidad segará, Y la vara de su insolencia se quebrará.\n",
    9: " El ojo misericordioso será bendito, Porque dio de su pan al indigente.\n",
    10: " Echa fuera al escarnecedor, y saldrá la contienda, Y cesará el pleito y la afrenta.\n",
    11: " El que ama la limpieza de corazón, Por la gracia de sus labios tendrá la amistad del rey.\n",
    12: " Los ojos de Jehová velan por la ciencia; Mas él trastorna las cosas de los prevaricadores.\n",
    13: " Dice el perezoso: El león está fuera; Seré muerto en la calle.\n",
    14: " Fosa profunda es la boca de la mujer extraña; Aquel contra el cual Jehová estuviere airado caerá en ella.\n",
    15: " La necedad está ligada en el corazón del muchacho; Mas la vara de la corrección la alejará de él.\n",
    16: " El que oprime al pobre para aumentar sus ganancias, O que da al rico, ciertamente se empobrecerá. Preceptos y amonestaciones\n",
    17: " Inclina tu oído y oye las palabras de los sabios, Y aplica tu corazón a mi sabiduría;\n",
    18: " Porque es cosa deliciosa, si las guardares dentro de ti; Si juntamente se afirmaren sobre tus labios.\n",
    19: " Para que tu confianza sea en Jehová, Te las he hecho saber hoy a ti también.\n",
    20: " ¿No te he escrito tres veces En consejos y en ciencia,\n",
    21: " Para hacerte saber la certidumbre de las palabras de verdad, A fin de que vuelvas a llevar palabras de verdad a los que te enviaron?\n",
    22: " No robes al pobre, porque es pobre, Ni quebrantes en la puerta al afligido;\n",
    23: " Porque Jehová juzgará la causa de ellos, Y despojará el alma de aquellos que los despojaren.\n",
    24: " No te entremetas con el iracundo, Ni te acompañes con el hombre de enojos,\n",
    25: " No sea que aprendas sus maneras, Y tomes lazo para tu alma.\n",
    26: " No seas de aquellos que se comprometen, Ni de los que salen por fiadores de deudas.\n",
    27: " Si no tuvieres para pagar, ¿Por qué han de quitar tu cama de debajo de ti?\n",
    28: " No traspases los linderos antiguos Que pusieron tus padres.\n",
    29: " ¿Has visto hombre solícito en su trabajo? Delante de los reyes estará; No estará delante de los de baja condición. ",
  },
  23: {
    1: " Cuando te sientes a comer con algún señor, Considera bien lo que está delante de ti,\n",
    2: " Y pon cuchillo a tu garganta, Si tienes gran apetito.\n",
    3: " No codicies sus manjares delicados, Porque es pan engañoso.\n",
    4: " No te afanes por hacerte rico; Sé prudente, y desiste.\n",
    5: " ¿Has de poner tus ojos en las riquezas, siendo ningunas? Porque se harán alas Como alas de águila, y volarán al cielo.\n",
    6: " No comas pan con el avaro, Ni codicies sus manjares;\n",
    7: " Porque cual es su pensamiento en su corazón, tal es él. Come y bebe, te dirá; Mas su corazón no está contigo.\n",
    8: " Vomitarás la parte que comiste, Y perderás tus suaves palabras.\n",
    9: " No hables a oídos del necio, Porque menospreciará la prudencia de tus razones.\n",
    10: " No traspases el lindero antiguo, Ni entres en la heredad de los huérfanos;\n",
    11: " Porque el defensor de ellos es el Fuerte, El cual juzgará la causa de ellos contra ti.\n",
    12: " Aplica tu corazón a la enseñanza, Y tus oídos a las palabras de sabiduría.\n",
    13: " No rehúses corregir al muchacho; Porque si lo castigas con vara, no morirá.\n",
    14: " Lo castigarás con vara, Y librarás su alma del Seol.\n",
    15: " Hijo mío, si tu corazón fuere sabio, También a mí se me alegrará el corazón;\n",
    16: " Mis entrañas también se alegrarán Cuando tus labios hablaren cosas rectas.\n",
    17: " No tenga tu corazón envidia de los pecadores, Antes persevera en el temor de Jehová todo el tiempo;\n",
    18: " Porque ciertamente hay fin, Y tu esperanza no será cortada.\n",
    19: " Oye, hijo mío, y sé sabio, Y endereza tu corazón al camino.\n",
    20: " No estés con los bebedores de vino, Ni con los comedores de carne;\n",
    21: " Porque el bebedor y el comilón empobrecerán, Y el sueño hará vestir vestidos rotos.\n",
    22: " Oye a tu padre, a aquel que te engendró; Y cuando tu madre envejeciere, no la menosprecies.\n",
    23: " Compra la verdad, y no la vendas; La sabiduría, la enseñanza y la inteligencia.\n",
    24: " Mucho se alegrará el padre del justo, Y el que engendra sabio se gozará con él.\n",
    25: " Alégrense tu padre y tu madre, Y gócese la que te dio a luz.\n",
    26: " Dame, hijo mío, tu corazón, Y miren tus ojos por mis caminos.\n",
    27: " Porque abismo profundo es la ramera, Y pozo angosto la extraña.\n",
    28: " También ella, como robador, acecha, Y multiplica entre los hombres los prevaricadores.\n",
    29: " ¿Para quién será el ay? ¿Para quién el dolor? ¿Para quién las rencillas? ¿Para quién las quejas? ¿Para quién las heridas en balde? ¿Para quién lo amoratado de los ojos?\n",
    30: " Para los que se detienen mucho en el vino, Para los que van buscando la mistura.\n",
    31: " No mires al vino cuando rojea, Cuando resplandece su color en la copa. Se entra suavemente;\n",
    32: " Mas al fin como serpiente morderá, Y como áspid dará dolor.\n",
    33: " Tus ojos mirarán cosas extrañas, Y tu corazón hablará perversidades.\n",
    34: " Serás como el que yace en medio del mar, O como el que está en la punta de un mastelero.\n",
    35: " Y dirás: Me hirieron, mas no me dolió; Me azotaron, mas no lo sentí; Cuando despertare, aún lo volveré a buscar. ",
  },
  24: {
    1: " No tengas envidia de los hombres malos, Ni desees estar con ellos;\n",
    2: " Porque su corazón piensa en robar, E iniquidad hablan sus labios.\n",
    3: " Con sabiduría se edificará la casa, Y con prudencia se afirmará;\n",
    4: " Y con ciencia se llenarán las cámaras De todo bien preciado y agradable.\n",
    5: " El hombre sabio es fuerte, Y de pujante vigor el hombre docto.\n",
    6: " Porque con ingenio harás la guerra, Y en la multitud de consejeros está la victoria.\n",
    7: " Alta está para el insensato la sabiduría; En la puerta no abrirá él su boca.\n",
    8: " Al que piensa hacer el mal, Le llamarán hombre de malos pensamientos.\n",
    9: " El pensamiento del necio es pecado, Y abominación a los hombres el escarnecedor.\n",
    10: " Si fueres flojo en el día de trabajo, Tu fuerza será reducida.\n",
    11: " Libra a los que son llevados a la muerte; Salva a los que están en peligro de muerte.\n",
    12: " Porque si dijeres: Ciertamente no lo supimos, ¿Acaso no lo entenderá el que pesa los corazones? El que mira por tu alma, él lo conocerá, Y dará al hombre según sus obras.\n",
    13: " Come, hijo mío, de la miel, porque es buena, Y el panal es dulce a tu paladar.\n",
    14: " Así será a tu alma el conocimiento de la sabiduría; Si la hallares tendrás recompensa, Y al fin tu esperanza no será cortada.\n",
    15: " Oh impío, no aceches la tienda del justo, No saquees su cámara;\n",
    16: " Porque siete veces cae el justo, y vuelve a levantarse; Mas los impíos caerán en el mal.\n",
    17: " Cuando cayere tu enemigo, no te regocijes, Y cuando tropezare, no se alegre tu corazón;\n",
    18: " No sea que Jehová lo mire, y le desagrade, Y aparte de sobre él su enojo.\n",
    19: " No te entremetas con los malignos, Ni tengas envidia de los impíos;\n",
    20: " Porque para el malo no habrá buen fin, Y la lámpara de los impíos será apagada.\n",
    21: " Teme a Jehová, hijo mío, y al rey; No te entremetas con los veleidosos;\n",
    22: " Porque su quebrantamiento vendrá de repente; Y el quebrantamiento de ambos, ¿quién lo comprende?\n",
    23: " También estos son dichos de los sabios: Hacer acepción de personas en el juicio no es bueno.\n",
    24: " El que dijere al malo: Justo eres, Los pueblos lo maldecirán, y le detestarán las naciones;\n",
    25: " Mas los que lo reprendieren tendrán felicidad, Y sobre ellos vendrá gran bendición.\n",
    26: " Besados serán los labios Del que responde palabras rectas.\n",
    27: " Prepara tus labores fuera, Y disponlas en tus campos, Y después edificarás tu casa.\n",
    28: " No seas sin causa testigo contra tu prójimo, Y no lisonjees con tus labios.\n",
    29: " No digas: Como me hizo, así le haré; Daré el pago al hombre según su obra.\n",
    30: " Pasé junto al campo del hombre perezoso, Y junto a la viña del hombre falto de entendimiento;\n",
    31: " Y he aquí que por toda ella habían crecido los espinos, Ortigas habían ya cubierto su faz, Y su cerca de piedra estaba ya destruida.\n",
    32: " Miré, y lo puse en mi corazón; Lo vi, y tomé consejo.\n",
    33: " Un poco de sueño, cabeceando otro poco, Poniendo mano sobre mano otro poco para dormir;\n",
    34: " Así vendrá como caminante tu necesidad, Y tu pobreza como hombre armado. ",
  },
  25: {
    1: " También estos son proverbios de Salomón, los cuales copiaron los varones de Ezequías, rey de Judá:\n",
    2: " Gloria de Dios es encubrir un asunto; Pero honra del rey es escudriñarlo.\n",
    3: " Para la altura de los cielos, y para la profundidad de la tierra, Y para el corazón de los reyes, no hay investigación.\n",
    4: " Quita las escorias de la plata, Y saldrá alhaja al fundidor.\n",
    5: " Aparta al impío de la presencia del rey, Y su trono se afirmará en justicia.\n",
    6: " No te alabes delante del rey, Ni estés en el lugar de los grandes;\n",
    7: " Porque mejor es que se te diga: Sube acá, Y no que seas humillado delante del príncipe A quien han mirado tus ojos.\n",
    8: " No entres apresuradamente en pleito, No sea que no sepas qué hacer al fin, Después que tu prójimo te haya avergonzado.\n",
    9: " Trata tu causa con tu compañero, Y no descubras el secreto a otro,\n",
    10: " No sea que te deshonre el que lo oyere, Y tu infamia no pueda repararse.\n",
    11: " Manzana de oro con figuras de plata Es la palabra dicha como conviene.\n",
    12: " Como zarcillo de oro y joyel de oro fino Es el que reprende al sabio que tiene oído dócil.\n",
    13: " Como frío de nieve en tiempo de la siega, Así es el mensajero fiel a los que lo envían, Pues al alma de su señor da refrigerio.\n",
    14: " Como nubes y vientos sin lluvia, Así es el hombre que se jacta de falsa liberalidad.\n",
    15: " Con larga paciencia se aplaca el príncipe, Y la lengua blanda quebranta los huesos.\n",
    16: " ¿Hallaste miel? Come lo que te basta, No sea que hastiado de ella la vomites.\n",
    17: " Detén tu pie de la casa de tu vecino, No sea que hastiado de ti te aborrezca.\n",
    18: " Martillo y cuchillo y saeta aguda Es el hombre que habla contra su prójimo falso testimonio.\n",
    19: " Como diente roto y pie descoyuntado Es la confianza en el prevaricador en tiempo de angustia.\n",
    20: " El que canta canciones al corazón afligido Es como el que quita la ropa en tiempo de frío, o el que sobre el jabón echa vinagre.\n",
    21: " Si el que te aborrece tuviere hambre, dale de comer pan, Y si tuviere sed, dale de beber agua;\n",
    22: " Porque ascuas amontonarás sobre su cabeza, Y Jehová te lo pagará.\n",
    23: " El viento del norte ahuyenta la lluvia, Y el rostro airado la lengua detractora.\n",
    24: " Mejor es estar en un rincón del terrado, Que con mujer rencillosa en casa espaciosa.\n",
    25: " Como el agua fría al alma sedienta, Así son las buenas nuevas de lejanas tierras.\n",
    26: " Como fuente turbia y manantial corrompido, Es el justo que cae delante del impío.\n",
    27: " Comer mucha miel no es bueno, Ni el buscar la propia gloria es gloria.\n",
    28: " Como ciudad derribada y sin muro Es el hombre cuyo espíritu no tiene rienda. ",
  },
  26: {
    1: " Como no conviene la nieve en el verano, ni la lluvia en la siega, Así no conviene al necio la honra.\n",
    2: " Como el gorrión en su vagar, y como la golondrina en su vuelo, Así la maldición nunca vendrá sin causa.\n",
    3: " El látigo para el caballo, el cabestro para el asno, Y la vara para la espalda del necio.\n",
    4: " Nunca respondas al necio de acuerdo con su necedad, Para que no seas tú también como él.\n",
    5: " Responde al necio como merece su necedad, Para que no se estime sabio en su propia opinión.\n",
    6: " Como el que se corta los pies y bebe su daño, Así es el que envía recado por mano de un necio.\n",
    7: " Las piernas del cojo penden inútiles; Así es el proverbio en la boca del necio.\n",
    8: " Como quien liga la piedra en la honda, Así hace el que da honra al necio.\n",
    9: " Espinas hincadas en mano del embriagado, Tal es el proverbio en la boca de los necios.\n",
    10: " Como arquero que a todos hiere, Es el que toma a sueldo insensatos y vagabundos.\n",
    11: " Como perro que vuelve a su vómito, Así es el necio que repite su necedad.\n",
    12: " ¿Has visto hombre sabio en su propia opinión? Más esperanza hay del necio que de él.\n",
    13: " Dice el perezoso: El león está en el camino; El león está en las calles.\n",
    14: " Como la puerta gira sobre sus quicios, Así el perezoso se vuelve en su cama.\n",
    15: " Mete el perezoso su mano en el plato; Se cansa de llevarla a su boca.\n",
    16: " En su propia opinión el perezoso es más sabio Que siete que sepan aconsejar.\n",
    17: " El que pasando se deja llevar de la ira en pleito ajeno Es como el que toma al perro por las orejas.\n",
    18: " Como el que enloquece, y echa llamas Y saetas y muerte,\n",
    19: " Tal es el hombre que engaña a su amigo, Y dice: Ciertamente lo hice por broma.\n",
    20: " Sin leña se apaga el fuego, Y donde no hay chismoso, cesa la contienda.\n",
    21: " El carbón para brasas, y la leña para el fuego; Y el hombre rencilloso para encender contienda.\n",
    22: " Las palabras del chismoso son como bocados suaves, Y penetran hasta las entrañas.\n",
    23: " Como escoria de plata echada sobre el tiesto Son los labios lisonjeros y el corazón malo.\n",
    24: " El que odia disimula con sus labios; Mas en su interior maquina engaño.\n",
    25: " Cuando hablare amigablemente, no le creas; Porque siete abominaciones hay en su corazón.\n",
    26: " Aunque su odio se cubra con disimulo, Su maldad será descubierta en la congregación.\n",
    27: " El que cava foso caerá en él; Y al que revuelve la piedra, sobre él le volverá.\n",
    28: " La lengua falsa atormenta al que ha lastimado, Y la boca lisonjera hace resbalar. ",
  },
  27: {
    1: " No te jactes del día de mañana; Porque no sabes qué dará de sí el día.\n",
    2: " Alábete el extraño, y no tu propia boca; El ajeno, y no los labios tuyos.\n",
    3: " Pesada es la piedra, y la arena pesa; Mas la ira del necio es más pesada que ambas.\n",
    4: " Cruel es la ira, e impetuoso el furor; Mas ¿quién podrá sostenerse delante de la envidia?\n",
    5: " Mejor es reprensión manifiesta Que amor oculto.\n",
    6: " Fieles son las heridas del que ama; Pero importunos los besos del que aborrece.\n",
    7: " El hombre saciado desprecia el panal de miel; Pero al hambriento todo lo amargo es dulce.\n",
    8: " Cual ave que se va de su nido, Tal es el hombre que se va de su lugar.\n",
    9: " El ungüento y el perfume alegran el corazón, Y el cordial consejo del amigo, al hombre.\n",
    10: " No dejes a tu amigo, ni al amigo de tu padre; Ni vayas a la casa de tu hermano en el día de tu aflicción. Mejor es el vecino cerca que el hermano lejos.\n",
    11: " Sé sabio, hijo mío, y alegra mi corazón, Y tendré qué responder al que me agravie.\n",
    12: " El avisado ve el mal y se esconde; Mas los simples pasan y llevan el daño.\n",
    13: " Quítale su ropa al que salió fiador por el extraño; Y al que fía a la extraña, tómale prenda.\n",
    14: " El que bendice a su amigo en alta voz, madrugando de mañana, Por maldición se le contará.\n",
    15: " Gotera continua en tiempo de lluvia Y la mujer rencillosa, son semejantes;\n",
    16: " Pretender contenerla es como refrenar el viento, O sujetar el aceite en la mano derecha.\n",
    17: " Hierro con hierro se aguza; Y así el hombre aguza el rostro de su amigo.\n",
    18: " Quien cuida la higuera comerá su fruto, Y el que mira por los intereses de su señor, tendrá honra.\n",
    19: " Como en el agua el rostro corresponde al rostro, Así el corazón del hombre al del hombre.\n",
    20: " El Seol y el Abadón nunca se sacian; Así los ojos del hombre nunca están satisfechos.\n",
    21: " El crisol prueba la plata, y la hornaza el oro, Y al hombre la boca del que lo alaba.\n",
    22: " Aunque majes al necio en un mortero entre granos de trigo majados con el pisón, No se apartará de él su necedad.\n",
    23: " Sé diligente en conocer el estado de tus ovejas, Y mira con cuidado por tus rebaños;\n",
    24: " Porque las riquezas no duran para siempre; ¿Y será la corona para perpetuas generaciones?\n",
    25: " Saldrá la grama, aparecerá la hierba, Y se segarán las hierbas de los montes.\n",
    26: " Los corderos son para tus vestidos, Y los cabritos para el precio del campo;\n",
    27: " Y abundancia de leche de las cabras para tu mantenimiento, para mantenimiento de tu casa, Y para sustento de tus criadas. ",
  },
  28: {
    1: " Huye el impío sin que nadie lo persiga; Mas el justo está confiado como un león.\n",
    2: " Por la rebelión de la tierra sus príncipes son muchos; Mas por el hombre entendido y sabio permanece estable.\n",
    3: " El hombre pobre y robador de los pobres Es como lluvia torrencial que deja sin pan.\n",
    4: " Los que dejan la ley alaban a los impíos; Mas los que la guardan contenderán con ellos.\n",
    5: " Los hombres malos no entienden el juicio; Mas los que buscan a Jehová entienden todas las cosas.\n",
    6: " Mejor es el pobre que camina en su integridad, Que el de perversos caminos y rico.\n",
    7: " El que guarda la ley es hijo prudente; Mas el que es compañero de glotones avergüenza a su padre.\n",
    8: " El que aumenta sus riquezas con usura y crecido interés, Para aquel que se compadece de los pobres las aumenta.\n",
    9: " El que aparta su oído para no oír la ley, Su oración también es abominable.\n",
    10: " El que hace errar a los rectos por el mal camino, El caerá en su misma fosa; Mas los perfectos heredarán el bien.\n",
    11: " El hombre rico es sabio en su propia opinión; Mas el pobre entendido lo escudriña.\n",
    12: " Cuando los justos se alegran, grande es la gloria; Mas cuando se levantan los impíos, tienen que esconderse los hombres.\n",
    13: " El que encubre sus pecados no prosperará; Mas el que los confiesa y se aparta alcanzará misericordia.\n",
    14: " Bienaventurado el hombre que siempre teme a Dios; Mas el que endurece su corazón caerá en el mal.\n",
    15: " León rugiente y oso hambriento Es el príncipe impío sobre el pueblo pobre.\n",
    16: " El príncipe falto de entendimiento multiplicará la extorsión; Mas el que aborrece la avaricia prolongará sus días.\n",
    17: " El hombre cargado de la sangre de alguno Huirá hasta el sepulcro, y nadie le detendrá.\n",
    18: " El que en integridad camina será salvo; Mas el de perversos caminos caerá en alguno.\n",
    19: " El que labra su tierra se saciará de pan; Mas el que sigue a los ociosos se llenará de pobreza.\n",
    20: " El hombre de verdad tendrá muchas bendiciones; Mas el que se apresura a enriquecerse no será sin culpa.\n",
    21: " Hacer acepción de personas no es bueno; Hasta por un bocado de pan prevaricará el hombre.\n",
    22: " Se apresura a ser rico el avaro, Y no sabe que le ha de venir pobreza.\n",
    23: " El que reprende al hombre, hallará después mayor gracia Que el que lisonjea con la lengua.\n",
    24: " El que roba a su padre o a su madre, y dice que no es maldad, Compañero es del hombre destruidor.\n",
    25: " El altivo de ánimo suscita contiendas; Mas el que confía en Jehová prosperará.\n",
    26: " El que confía en su propio corazón es necio; Mas el que camina en sabiduría será librado.\n",
    27: " El que da al pobre no tendrá pobreza; Mas el que aparta sus ojos tendrá muchas maldiciones.\n",
    28: " Cuando los impíos son levantados se esconde el hombre; Mas cuando perecen, los justos se multiplican. ",
  },
  29: {
    1: " El hombre que reprendido endurece la cerviz, De repente será quebrantado, y no habrá para él medicina.\n",
    2: " Cuando los justos dominan, el pueblo se alegra; Mas cuando domina el impío, el pueblo gime.\n",
    3: " El hombre que ama la sabiduría alegra a su padre; Mas el que frecuenta rameras perderá los bienes.\n",
    4: " El rey con el juicio afirma la tierra; Mas el que exige presentes la destruye.\n",
    5: " El hombre que lisonjea a su prójimo, Red tiende delante de sus pasos.\n",
    6: " En la transgresión del hombre malo hay lazo; Mas el justo cantará y se alegrará.\n",
    7: " Conoce el justo la causa de los pobres; Mas el impío no entiende sabiduría.\n",
    8: " Los hombres escarnecedores ponen la ciudad en llamas; Mas los sabios apartan la ira.\n",
    9: " Si el hombre sabio contendiere con el necio, Que se enoje o que se ría, no tendrá reposo.\n",
    10: " Los hombres sanguinarios aborrecen al perfecto, Mas los rectos buscan su contentamiento.\n",
    11: " El necio da rienda suelta a toda su ira, Mas el sabio al fin la sosiega.\n",
    12: " Si un gobernante atiende la palabra mentirosa, Todos sus servidores serán impíos.\n",
    13: " El pobre y el usurero se encuentran; Jehová alumbra los ojos de ambos.\n",
    14: " Del rey que juzga con verdad a los pobres, El trono será firme para siempre.\n",
    15: " La vara y la corrección dan sabiduría; Mas el muchacho consentido avergonzará a su madre.\n",
    16: " Cuando los impíos son muchos, mucha es la transgresión; Mas los justos verán la ruina de ellos.\n",
    17: " Corrige a tu hijo, y te dará descanso, Y dará alegría a tu alma.\n",
    18: " Sin profecía el pueblo se desenfrena; Mas el que guarda la ley es bienaventurado.\n",
    19: " El siervo no se corrige con palabras; Porque entiende, mas no hace caso.\n",
    20: " ¿Has visto hombre ligero en sus palabras? Más esperanza hay del necio que de él.\n",
    21: " El siervo mimado desde la niñez por su amo, A la postre será su heredero.\n",
    22: " El hombre iracundo levanta contiendas, Y el furioso muchas veces peca.\n",
    23: " La soberbia del hombre le abate; Pero al humilde de espíritu sustenta la honra.\n",
    24: " El cómplice del ladrón aborrece su propia alma; Pues oye la imprecación y no dice nada.\n",
    25: " El temor del hombre pondrá lazo; Mas el que confía en Jehová será exaltado.\n",
    26: " Muchos buscan el favor del príncipe; Mas de Jehová viene el juicio de cada uno.\n",
    27: " Abominación es a los justos el hombre inicuo; Y abominación es al impío el de caminos rectos. ",
  },
  30: {
    1: " Palabras de Agur, hijo de Jaqué; la profecía que dijo el varón a Itiel, a Itiel y a Ucal.\n",
    2: " Ciertamente más rudo soy yo que ninguno, Ni tengo entendimiento de hombre.\n",
    3: " Yo ni aprendí sabiduría, Ni conozco la ciencia del Santo.\n",
    4: " ¿Quién subió al cielo, y descendió? ¿Quién encerró los vientos en sus puños? ¿Quién ató las aguas en un paño? ¿Quién afirmó todos los términos de la tierra? ¿Cuál es su nombre, y el nombre de su hijo, si sabes?\n",
    5: " Toda palabra de Dios es limpia; El es escudo a los que en él esperan.\n",
    6: " No añadas a sus palabras, para que no te reprenda, Y seas hallado mentiroso.\n",
    7: " Dos cosas te he demandado; No me las niegues antes que muera:\n",
    8: " Vanidad y palabra mentirosa aparta de mí; No me des pobreza ni riquezas; Manténme del pan necesario;\n",
    9: " No sea que me sacie, y te niegue, y diga: ¿Quién es Jehová? O que siendo pobre, hurte, Y blasfeme el nombre de mi Dios.\n",
    10: " No acuses al siervo ante su señor, No sea que te maldiga, y lleves el castigo.\n",
    11: " Hay generación que maldice a su padre Y a su madre no bendice.\n",
    12: " Hay generación limpia en su propia opinión, Si bien no se ha limpiado de su inmundicia.\n",
    13: " Hay generación cuyos ojos son altivos Y cuyos párpados están levantados en alto.\n",
    14: " Hay generación cuyos dientes son espadas, y sus muelas cuchillos, Para devorar a los pobres de la tierra, y a los menesterosos de entre los hombres.\n",
    15: " La sanguijuela tiene dos hijas que dicen: ¡Dame! ¡dame! Tres cosas hay que nunca se sacian; Aun la cuarta nunca dice: ¡Basta!\n",
    16: " El Seol, la matriz estéril, La tierra que no se sacia de aguas, Y el fuego que jamás dice: ¡Basta!\n",
    17: " El ojo que escarnece a su padre Y menosprecia la enseñanza de la madre, Los cuervos de la cañada lo saquen, Y lo devoren los hijos del águila.\n",
    18: " Tres cosas me son ocultas; Aun tampoco sé la cuarta:\n",
    19: " El rastro del águila en el aire; El rastro de la culebra sobre la peña; El rastro de la nave en medio del mar; Y el rastro del hombre en la doncella.\n",
    20: " El proceder de la mujer adúltera es así: Come, y limpia su boca Y dice: No he hecho maldad.\n",
    21: " Por tres cosas se alborota la tierra, Y la cuarta ella no puede sufrir:\n",
    22: " Por el siervo cuando reina; Por el necio cuando se sacia de pan;\n",
    23: " Por la mujer odiada cuando se casa; Y por la sierva cuando hereda a su señora.\n",
    24: " Cuatro cosas son de las más pequeñas de la tierra, Y las mismas son más sabias que los sabios:\n",
    25: " Las hormigas, pueblo no fuerte, Y en el verano preparan su comida;\n",
    26: " Los conejos, pueblo nada esforzado, Y ponen su casa en la piedra;\n",
    27: " Las langostas, que no tienen rey, Y salen todas por cuadrillas;\n",
    28: " La araña que atrapas con la mano, Y está en palacios de rey.\n",
    29: " Tres cosas hay de hermoso andar, Y la cuarta pasea muy bien:\n",
    30: " El león, fuerte entre todos los animales, Que no vuelve atrás por nada;\n",
    31: " El ceñido de lomos; asimismo el macho cabrío; Y el rey, a quien nadie resiste.\n",
    32: " Si neciamente has procurado enaltecerte, O si has pensado hacer mal, Pon el dedo sobre tu boca.\n",
    33: " Ciertamente el que bate la leche sacará mantequilla, Y el que recio se suena las narices sacará sangre; Y el que provoca la ira causará contienda. ",
  },
  31: {
    1: " Palabras del rey Lemuel; la profecía con que le enseñó su madre.\n",
    2: " ¿Qué, hijo mío? ¿y qué, hijo de mi vientre? ¿Y qué, hijo de mis deseos?\n",
    3: " No des a las mujeres tu fuerza, Ni tus caminos a lo que destruye a los reyes.\n",
    4: " No es de los reyes, oh Lemuel, no es de los reyes beber vino, Ni de los príncipes la sidra;\n",
    5: " No sea que bebiendo olviden la ley, Y perviertan el derecho de todos los afligidos.\n",
    6: " Dad la sidra al desfallecido, Y el vino a los de amargado ánimo.\n",
    7: " Beban, y olvídense de su necesidad, Y de su miseria no se acuerden más.\n",
    8: " Abre tu boca por el mudo En el juicio de todos los desvalidos.\n",
    9: " Abre tu boca, juzga con justicia, Y defiende la causa del pobre y del menesteroso. Elogio de la mujer virtuosa\n",
    10: " Mujer virtuosa, ¿quién la hallará? Porque su estima sobrepasa largamente a la de las piedras preciosas.\n",
    11: " El corazón de su marido está en ella confiado, Y no carecerá de ganancias.\n",
    12: " Le da ella bien y no mal Todos los días de su vida.\n",
    13: " Busca lana y lino, Y con voluntad trabaja con sus manos.\n",
    14: " Es como nave de mercader; Trae su pan de lejos.\n",
    15: " Se levanta aun de noche Y da comida a su familia Y ración a sus criadas.\n",
    16: " Considera la heredad, y la compra, Y planta viña del fruto de sus manos.\n",
    17: " Ciñe de fuerza sus lomos, Y esfuerza sus brazos.\n",
    18: " Ve que van bien sus negocios; Su lámpara no se apaga de noche.\n",
    19: " Aplica su mano al huso, Y sus manos a la rueca.\n",
    20: " Alarga su mano al pobre, Y extiende sus manos al menesteroso.\n",
    21: " No tiene temor de la nieve por su familia, Porque toda su familia está vestida de ropas dobles.\n",
    22: " Ella se hace tapices; De lino fino y púrpura es su vestido.\n",
    23: " Su marido es conocido en las puertas, Cuando se sienta con los ancianos de la tierra.\n",
    24: " Hace telas, y vende, Y da cintas al mercader.\n",
    25: " Fuerza y honor son su vestidura; Y se ríe de lo por venir.\n",
    26: " Abre su boca con sabiduría, Y la ley de clemencia está en su lengua.\n",
    27: " Considera los caminos de su casa, Y no come el pan de balde.\n",
    28: " Se levantan sus hijos y la llaman bienaventurada; Y su marido también la alaba:\n",
    29: " Muchas mujeres hicieron el bien; Mas tú sobrepasas a todas.\n",
    30: " Engañosa es la gracia, y vana la hermosura; La mujer que teme a Jehová, ésa será alabada.\n",
    31: " Dadle del fruto de sus manos, Y alábenla en las puertas sus hechos. ",
  },
};
export default proverbios;
