const tesalonicences2 = {
  1: {
    1: " Pablo, Silvano y Timoteo, a la iglesia de los tesalonicenses en Dios nuestro Padre y en el Señor Jesucristo:\n",
    2: " Gracia y paz a vosotros, de Dios nuestro Padre y del Señor Jesucristo.\n",
    3: " Debemos siempre dar gracias a Dios por vosotros, hermanos, como es digno, por cuanto vuestra fe va creciendo, y el amor de todos y cada uno de vosotros abunda para con los demás;\n",
    4: " tanto, que nosotros mismos nos gloriamos de vosotros en las iglesias de Dios, por vuestra paciencia y fe en todas vuestras persecuciones y tribulaciones que soportáis.\n",
    5: " Esto es demostración del justo juicio de Dios, para que seáis tenidos por dignos del reino de Dios, por el cual asimismo padecéis.\n",
    6: " Porque es justo delante de Dios pagar con tribulación a los que os atribulan,\n",
    7: " y a vosotros que sois atribulados, daros reposo con nosotros, cuando se manifieste el Señor Jesús desde el cielo con los ángeles de su poder,\n",
    8: " en llama de fuego, para dar retribución a los que no conocieron a Dios, ni obedecen al evangelio de nuestro Señor Jesucristo;\n",
    9: " los cuales sufrirán pena de eterna perdición, excluidos de la presencia del Señor y de la gloria de su poder,\n",
    10: " cuando venga en aquel día para ser glorificado en sus santos y ser admirado en todos los que creyeron (por cuanto nuestro testimonio ha sido creído entre vosotros).\n",
    11: " Por lo cual asimismo oramos siempre por vosotros, para que nuestro Dios os tenga por dignos de su llamamiento, y cumpla todo propósito de bondad y toda obra de fe con su poder,\n",
    12: " para que el nombre de nuestro Señor Jesucristo sea glorificado en vosotros, y vosotros en él, por la gracia de nuestro Dios y del Señor Jesucristo. ",
  },
  2: {
    1: " Pero con respecto a la venida de nuestro Señor Jesucristo, y nuestra reunión con él, os rogamos, hermanos,\n",
    2: " que no os dejéis mover fácilmente de vuestro modo de pensar, ni os conturbéis, ni por espíritu, ni por palabra, ni por carta como si fuera nuestra, en el sentido de que el día del Señor está cerca.\n",
    3: " Nadie os engañe en ninguna manera; porque no vendrá sin que antes venga la apostasía, y se manifieste el hombre de pecado, el hijo de perdición,\n",
    4: " el cual se opone y se levanta contra todo lo que se llama Dios o es objeto de culto; tanto que se sienta en el templo de Dios como Dios, haciéndose pasar por Dios.\n",
    5: " ¿No os acordáis que cuando yo estaba todavía con vosotros, os decía esto?\n",
    6: " Y ahora vosotros sabéis lo que lo detiene, a fin de que a su debido tiempo se manifieste.\n",
    7: " Porque ya está en acción el misterio de la iniquidad; sólo que hay quien al presente lo detiene, hasta que él a su vez sea quitado de en medio.\n",
    8: " Y entonces se manifestará aquel inicuo, a quien el Señor matará con el espíritu de su boca, y destruirá con el resplandor de su venida;\n",
    9: " inicuo cuyo advenimiento es por obra de Satanás, con gran poder y señales y prodigios mentirosos,\n",
    10: " y con todo engaño de iniquidad para los que se pierden, por cuanto no recibieron el amor de la verdad para ser salvos.\n",
    11: " Por esto Dios les envía un poder engañoso, para que crean la mentira,\n",
    12: " a fin de que sean condenados todos los que no creyeron a la verdad, sino que se complacieron en la injusticia.\n",
    13: " Pero nosotros debemos dar siempre gracias a Dios respecto a vosotros, hermanos amados por el Señor, de que Dios os haya escogido desde el principio para salvación, mediante la santificación por el Espíritu y la fe en la verdad,\n",
    14: " a lo cual os llamó mediante nuestro evangelio, para alcanzar la gloria de nuestro Señor Jesucristo.\n",
    15: " Así que, hermanos, estad firmes, y retened la doctrina que habéis aprendido, sea por palabra, o por carta nuestra.\n",
    16: " Y el mismo Jesucristo Señor nuestro, y Dios nuestro Padre, el cual nos amó y nos dio consolación eterna y buena esperanza por gracia,\n",
    17: " conforte vuestros corazones, y os confirme en toda buena palabra y obra. ",
  },
  3: {
    1: " Por lo demás, hermanos, orad por nosotros, para que la palabra del Señor corra y sea glorificada, así como lo fue entre vosotros,\n",
    2: " y para que seamos librados de hombres perversos y malos; porque no es de todos la fe.\n",
    3: " Pero fiel es el Señor, que os afirmará y guardará del mal.\n",
    4: " Y tenemos confianza respecto a vosotros en el Señor, en que hacéis y haréis lo que os hemos mandado.\n",
    5: " Y el Señor encamine vuestros corazones al amor de Dios, y a la paciencia de Cristo.\n",
    6: " Pero os ordenamos, hermanos, en el nombre de nuestro Señor Jesucristo, que os apartéis de todo hermano que ande desordenadamente, y no según la enseñanza que recibisteis de nosotros.\n",
    7: " Porque vosotros mismos sabéis de qué manera debéis imitarnos; pues nosotros no anduvimos desordenadamente entre vosotros,\n",
    8: " ni comimos de balde el pan de nadie, sino que trabajamos con afán y fatiga día y noche, para no ser gravosos a ninguno de vosotros;\n",
    9: " no porque no tuviésemos derecho, sino por daros nosotros mismos un ejemplo para que nos imitaseis.\n",
    10: " Porque también cuando estábamos con vosotros, os ordenábamos esto: Si alguno no quiere trabajar, tampoco coma.\n",
    11: " Porque oímos que algunos de entre vosotros andan desordenadamente, no trabajando en nada, sino entremetiéndose en lo ajeno.\n",
    12: " A los tales mandamos y exhortamos por nuestro Señor Jesucristo, que trabajando sosegadamente, coman su propio pan.\n",
    13: " Y vosotros, hermanos, no os canséis de hacer bien.\n",
    14: " Si alguno no obedece a lo que decimos por medio de esta carta, a ése señaladlo, y no os juntéis con él, para que se avergüence.\n",
    15: " Mas no lo tengáis por enemigo, sino amonestadle como a hermano.\n",
    16: " Y el mismo Señor de paz os dé siempre paz en toda manera. El Señor sea con todos vosotros.\n",
    17: " La salutación es de mi propia mano, de Pablo, que es el signo en toda carta mía; así escribo.\n",
    18: " La gracia de nuestro Señor Jesucristo sea con todos vosotros. Amén. ",
  },
};
export default tesalonicences2;
