const timoteo2 = {
  1: {
    1: " Pablo, apóstol de Jesucristo por la voluntad de Dios, según la promesa de la vida que es en Cristo Jesús,\n",
    2: " a Timoteo, amado hijo: Gracia, misericordia y paz, de Dios Padre y de Jesucristo nuestro Señor.\n",
    3: " Doy gracias a Dios, al cual sirvo desde mis mayores con limpia conciencia, de que sin cesar me acuerdo de ti en mis oraciones noche y día;\n",
    4: " deseando verte, al acordarme de tus lágrimas, para llenarme de gozo;\n",
    5: " trayendo a la memoria la fe no fingida que hay en ti, la cual habitó primero en tu abuela Loida, y en tu madre Eunice, y estoy seguro que en ti también.\n",
    6: " Por lo cual te aconsejo que avives el fuego del don de Dios que está en ti por la imposición de mis manos.\n",
    7: " Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio.\n",
    8: " Por tanto, no te avergüences de dar testimonio de nuestro Señor, ni de mí, preso suyo, sino participa de las aflicciones por el evangelio según el poder de Dios,\n",
    9: " quien nos salvó y llamó con llamamiento santo, no conforme a nuestras obras, sino según el propósito suyo y la gracia que nos fue dada en Cristo Jesús antes de los tiempos de los siglos,\n",
    10: " pero que ahora ha sido manifestada por la aparición de nuestro Salvador Jesucristo, el cual quitó la muerte y sacó a luz la vida y la inmortalidad por el evangelio,\n",
    11: " del cual yo fui constituido predicador, apóstol y maestro de los gentiles.\n",
    12: " Por lo cual asimismo padezco esto; pero no me avergüenzo, porque yo sé a quién he creído, y estoy seguro que es poderoso para guardar mi depósito para aquel día.\n",
    13: " Retén la forma de las sanas palabras que de mí oíste, en la fe y amor que es en Cristo Jesús.\n",
    14: " Guarda el buen depósito por el Espíritu Santo que mora en nosotros.\n",
    15: " Ya sabes esto, que me abandonaron todos los que están en Asia, de los cuales son Figelo y Hermógenes.\n",
    16: " Tenga el Señor misericordia de la casa de Onesíforo, porque muchas veces me confortó, y no se avergonzó de mis cadenas,\n",
    17: " sino que cuando estuvo en Roma, me buscó solícitamente y me halló.\n",
    18: " Concédale el Señor que halle misericordia cerca del Señor en aquel día. Y cuánto nos ayudó en Efeso, tú lo sabes mejor. ",
  },
  2: {
    1: " Tú, pues, hijo mío, esfuérzate en la gracia que es en Cristo Jesús.\n",
    2: " Lo que has oído de mí ante muchos testigos, esto encarga a hombres fieles que sean idóneos para enseñar también a otros.\n",
    3: " Tú, pues, sufre penalidades como buen soldado de Jesucristo.\n",
    4: " Ninguno que milita se enreda en los negocios de la vida, a fin de agradar a aquel que lo tomó por soldado.\n",
    5: " Y también el que lucha como atleta, no es coronado si no lucha legítimamente.\n",
    6: " El labrador, para participar de los frutos, debe trabajar primero.\n",
    7: " Considera lo que digo, y el Señor te dé entendimiento en todo.\n",
    8: " Acuérdate de Jesucristo, del linaje de David, resucitado de los muertos conforme a mi evangelio,\n",
    9: " en el cual sufro penalidades, hasta prisiones a modo de malhechor; mas la palabra de Dios no está presa.\n",
    10: " Por tanto, todo lo soporto por amor de los escogidos, para que ellos también obtengan la salvación que es en Cristo Jesús con gloria eterna.\n",
    11: " Palabra fiel es esta: Si somos muertos con él, también viviremos con él;\n",
    12: " Si sufrimos, también reinaremos con él; Si le negáremos, él también nos negará.\n",
    13: " Si fuéremos infieles, él permanece fiel; El no puede negarse a sí mismo.\n",
    14: " Recuérdales esto, exhortándoles delante del Señor a que no contiendan sobre palabras, lo cual para nada aprovecha, sino que es para perdición de los oyentes.\n",
    15: " Procura con diligencia presentarte a Dios aprobado, como obrero que no tiene de qué avergonzarse, que usa bien la palabra de verdad.\n",
    16: " Mas evita profanas y vanas palabrerías, porque conducirán más y más a la impiedad.\n",
    17: " Y su palabra carcomerá como gangrena; de los cuales son Himeneo y Fileto,\n",
    18: " que se desviaron de la verdad, diciendo que la resurrección ya se efectuó, y trastornan la fe de algunos.\n",
    19: " Pero el fundamento de Dios está firme, teniendo este sello: Conoce el Señor a los que son suyos; y: Apártese de iniquidad todo aquel que invoca el nombre de Cristo.\n",
    20: " Pero en una casa grande, no solamente hay utensilios de oro y de plata, sino también de madera y de barro; y unos son para usos honrosos, y otros para usos viles.\n",
    21: " Así que, si alguno se limpia de estas cosas, será instrumento para honra, santificado, útil al Señor, y dispuesto para toda buena obra.\n",
    22: " Huye también de las pasiones juveniles, y sigue la justicia, la fe, el amor y la paz, con los que de corazón limpio invocan al Señor.\n",
    23: " Pero desecha las cuestiones necias e insensatas, sabiendo que engendran contiendas.\n",
    24: " Porque el siervo del Señor no debe ser contencioso, sino amable para con todos, apto para enseñar, sufrido;\n",
    25: " que con mansedumbre corrija a los que se oponen, por si quizá Dios les conceda que se arrepientan para conocer la verdad,\n",
    26: " y escapen del lazo del diablo, en que están cautivos a voluntad de él. ",
  },
  3: {
    1: " También debes saber esto: que en los postreros días vendrán tiempos peligrosos.\n",
    2: " Porque habrá hombres amadores de sí mismos, avaros, vanagloriosos, soberbios, blasfemos, desobedientes a los padres, ingratos, impíos,\n",
    3: " sin afecto natural, implacables, calumniadores, intemperantes, crueles, aborrecedores de lo bueno,\n",
    4: " traidores, impetuosos, infatuados, amadores de los deleites más que de Dios,\n",
    5: " que tendrán apariencia de piedad, pero negarán la eficacia de ella; a éstos evita.\n",
    6: " Porque de éstos son los que se meten en las casas y llevan cautivas a las mujercillas cargadas de pecados, arrastradas por diversas concupiscencias.\n",
    7: " Estas siempre están aprendiendo, y nunca pueden llegar al conocimiento de la verdad.\n",
    8: " Y de la manera que Janes y Jambres resistieron a Moisés, así también éstos resisten a la verdad; hombres corruptos de entendimiento, réprobos en cuanto a la fe.\n",
    9: " Mas no irán más adelante; porque su insensatez será manifiesta a todos, como también lo fue la de aquéllos.\n",
    10: " Pero tú has seguido mi doctrina, conducta, propósito, fe, longanimidad, amor, paciencia,\n",
    11: " persecuciones, padecimientos, como los que me sobrevinieron en Antioquía, en Iconio, en Listra; persecuciones que he sufrido, y de todas me ha librado el Señor.\n",
    12: " Y también todos los que quieren vivir piadosamente en Cristo Jesús padecerán persecución;\n",
    13: " mas los malos hombres y los engañadores irán de mal en peor, engañando y siendo engañados.\n",
    14: " Pero persiste tú en lo que has aprendido y te persuadiste, sabiendo de quién has aprendido;\n",
    15: " y que desde la niñez has sabido las Sagradas Escrituras, las cuales te pueden hacer sabio para la salvación por la fe que es en Cristo Jesús.\n",
    16: " Toda la Escritura es inspirada por Dios, y útil para enseñar, para redargüir, para corregir, para instruir en justicia,\n",
    17: " a fin de que el hombre de Dios sea perfecto, enteramente preparado para toda buena obra. ",
  },
  4: {
    1: " Te encarezco delante de Dios y del Señor Jesucristo, que juzgará a los vivos y a los muertos en su manifestación y en su reino,\n",
    2: " que prediques la palabra; que instes a tiempo y fuera de tiempo; redarguye, reprende, exhorta con toda paciencia y doctrina.\n",
    3: " Porque vendrá tiempo cuando no sufrirán la sana doctrina, sino que teniendo comezón de oír, se amontonarán maestros conforme a sus propias concupiscencias,\n",
    4: " y apartarán de la verdad el oído y se volverán a las fábulas.\n",
    5: " Pero tú sé sobrio en todo, soporta las aflicciones, haz obra de evangelista, cumple tu ministerio.\n",
    6: " Porque yo ya estoy para ser sacrificado, y el tiempo de mi partida está cercano.\n",
    7: " He peleado la buena batalla, he acabado la carrera, he guardado la fe.\n",
    8: " Por lo demás, me está guardada la corona de justicia, la cual me dará el Señor, juez justo, en aquel día; y no sólo a mí, sino también a todos los que aman su venida.\n",
    9: " Procura venir pronto a verme,\n",
    10: " porque Demas me ha desamparado, amando este mundo, y se ha ido a Tesalónica. Crescente fue a Galacia, y Tito a Dalmacia.\n",
    11: " Sólo Lucas está conmigo. Toma a Marcos y tráele contigo, porque me es útil para el ministerio.\n",
    12: " A Tíquico lo envié a Efeso.\n",
    13: " Trae, cuando vengas, el capote que dejé en Troas en casa de Carpo, y los libros, mayormente los pergaminos.\n",
    14: " Alejandro el calderero me ha causado muchos males; el Señor le pague conforme a sus hechos.\n",
    15: " Guárdate tú también de él, pues en gran manera se ha opuesto a nuestras palabras.\n",
    16: " En mi primera defensa ninguno estuvo a mi lado, sino que todos me desampararon; no les sea tomado en cuenta.\n",
    17: " Pero el Señor estuvo a mi lado, y me dio fuerzas, para que por mí fuese cumplida la predicación, y que todos los gentiles oyesen. Así fui librado de la boca del león.\n",
    18: " Y el Señor me librará de toda obra mala, y me preservará para su reino celestial. A él sea gloria por los siglos de los siglos. Amén.\n",
    19: " Saluda a Prisca y a Aquila, y a la casa de Onesíforo.\n",
    20: " Erasto se quedó en Corinto, y a Trófimo dejé en Mileto enfermo.\n",
    21: " Procura venir antes del invierno. Eubulo te saluda, y Pudente, Lino, Claudia y todos los hermanos.\n",
    22: " El Señor Jesucristo esté con tu espíritu. La gracia sea con vosotros. Amén. ",
  },
};
export default timoteo2;
