const bible = {
  genesis: {
    1: {
      1: "En el principio creó Dios los cielos y la tierra.",
      2: "Y la tierra estaba desordenada y vacía, y las tinieblas estaban sobre la faz del abismo, y el Espíritu de Dios se movía sobre la faz de las aguas.",

      3: "Y dijo Dios: Sea la luz; y fue la luz.",
      4: "Y vio Dios que la luz era buena; y separó Dios la luz de las tinieblas.",
      5: "Y llamó Dios a la luz Día, y a las tinieblas llamó Noche. Y fue la tarde y la mañana un día.",

      6: "Luego dijo Dios: Haya expansión en medio de las aguas, y separe las aguas de las aguas.",
      7: "E hizo Dios la expansión, y separó las aguas que estaban debajo de la expansión, de las aguas que estaban sobre la expansión. Y fue así.",
      8: "Y llamó Dios a la expansión Cielos. Y fue la tarde y la mañana el día segundo.",

      9: "Dijo también Dios: Júntense las aguas que están debajo de los cielos en un lugar, y descúbrase lo seco. Y fue así.",
      10: "Y llamó Dios a lo seco Tierra, y a la reunión de las aguas llamó Mares. Y vio Dios que era bueno.",
      11: "Después dijo Dios: Produzca la tierra hierba verde, hierba que dé semilla; árbol de fruto que dé fruto según su género, que su semilla esté en él, sobre la tierra. Y fue así.",
      12: "Produjo, pues, la tierra hierba verde, hierba que da semilla según su naturaleza, y árbol que da fruto, cuya semilla está en él, según su género. Y vio Dios que era bueno.",
      13: "Y fue la tarde y la mañana el día tercero.",

      14: "Dijo luego Dios: Haya lumbreras en la expansión de los cielos para separar el día de la noche; y sirvan de señales para las estaciones, para días y años,",
      15: "y sean por lumbreras en la expansión de los cielos para alumbrar sobre la tierra. Y fue así.",
      16: "E hizo Dios las dos grandes lumbreras; la lumbrera mayor para que señorease en el día, y la lumbrera menor para que señorease en la noche; hizo también las estrellas.",
      17: "Y las puso Dios en la expansión de los cielos para alumbrar sobre la tierra,",
      18: "y para señorear en el día y en la noche, y para separar la luz de las tinieblas. Y vio Dios que era bueno.",
      19: "Y fue la tarde y la mañana el día cuarto.",
      20: "Dijo Dios: Produzcan las aguas seres vivientes, y aves que vuelen sobre la tierra, en la abierta expansión de los cielos.",
      21: "Y creó Dios los grandes monstruos marinos, y todo ser viviente que se mueve, que las aguas produjeron según su género, y toda ave alada según su especie. Y vio Dios que era bueno.",
      22: "Y Dios los bendijo, diciendo: Fructificad y multiplicaos, y llenad las aguas en los mares, y multiplíquense las aves en la tierra.",
      23: "Y fue la tarde y la mañana el día quinto.",

      24: "Luego dijo Dios: Produzca la tierra seres vivientes según su género, bestias y serpientes y animales de la tierra según su especie. Y fue así.",
      25: "E hizo Dios animales de la tierra según su género, y ganado según su género, y todo animal que se arrastra sobre la tierra según su especie. Y vio Dios que era bueno.",

      26: "Entonces dijo Dios: Hagamos al hombre a nuestra imagen, conforme a nuestra semejanza; y señoree en los peces del mar, en las aves de los cielos, en las bestias, en toda la tierra, y en todo animal que se arrastra sobre la tierra.",
      27: "Y creó Dios al hombre a su imagen, a imagen de Dios lo creó; varón y hembra los creó.",
      28: "Y los bendijo Dios, y les dijo: Fructificad y multiplicaos; llenad la tierra, y sojuzgadla, y señoread en los peces del mar, en las aves de los cielos, y en todas las bestias que se mueven sobre la tierra.",

      29: "Y dijo Dios: He aquí que os he dado toda planta que da semilla, que está sobre toda la tierra, y todo árbol en que hay fruto y que da semilla; os serán para comer. 30 Y a toda bestia de la tierra, y a todas las aves de los cielos, y a todo lo que se arrastra sobre la tierra, en que hay vida, toda planta verde les será para comer. Y fue así.",
      31: "Y vio Dios todo lo que había hecho, y he aquí que era bueno en gran manera. Y fue la tarde y la mañana el día sexto.",
    },
    2: {
      1: "Fueron, pues, acabados los cielos y la tierra, y todo el ejército de ellos.",
      2: "Y acabó Dios en el día séptimo la obra que hizo; y reposó el día séptimo de toda la obra que hizo.",
      3: "Y bendijo Dios al día séptimo, y lo santificó, porque en él reposó de toda la obra que había hecho en la creación.",

      4: "Estos son los orígenes de los cielos y de la tierra cuando fueron creados, el día que Jehová Dios hizo la tierra y los cielos,",
      5: "y toda planta del campo antes que fuese en la tierra, y toda hierba del campo antes que naciese; porque Jehová Dios aún no había hecho llover sobre la tierra, ni había hombre para que labrase la tierra,",
      6: "sino que subía de la tierra un vapor, el cual regaba toda la faz de la tierra.",
      7: "Entonces Jehová Dios formó al hombre del polvo de la tierra, y sopló en su nariz aliento de vida, y fue el hombre un ser viviente.",

      8: "Y Jehová Dios plantó un huerto en Edén, al oriente; y puso allí al hombre que había formado.",
      9: "Y Jehová Dios hizo nacer de la tierra todo árbol delicioso a la vista, y bueno para comer; también el árbol de vida en medio del huerto, y el árbol de la ciencia del bien y del mal.",
      10: "Y salía de Edén un río para regar el huerto, y de allí se repartía en cuatro brazos.",
      11: "El nombre del uno era Pisón; este es el que rodea toda la tierra de Havila, donde hay oro;",
      12: "y el oro de aquella tierra es bueno; hay allí también bedelio y ónice. 13 El nombre del segundo río es Gihón; este es el que rodea toda la tierra de Cus.",
      14: "Y el nombre del tercer río es Hidekel; este es el que va al oriente de Asiria. Y el cuarto río es el Éufrates.",

      15: "Tomó, pues, Jehová Dios al hombre, y lo puso en el huerto de Edén, para que lo labrara y lo guardase.",
      16: "Y mandó Jehová Dios al hombre, diciendo: De todo árbol del huerto podrás comer;",
      17: "mas del árbol de la ciencia del bien y del mal no comerás; porque el día que de él comieres, ciertamente morirás.",

      18: "Y dijo Jehová Dios: No es bueno que el hombre esté solo; le haré ayuda idónea para él.",
      19: "Jehová Dios formó, pues, de la tierra toda bestia del campo, y toda ave de los cielos, y las trajo a Adán para que viese cómo las había de llamar; y todo lo que Adán llamó a los animales vivientes, ese es su nombre.",
      20: "Y puso Adán nombre a toda bestia y ave de los cielos y a todo ganado del campo; mas para Adán no se halló ayuda idónea para él. 21 Entonces Jehová Dios hizo caer sueño profundo sobre Adán, y mientras este dormía, tomó una de sus costillas, y cerró la carne en su lugar.",
      22: "Y de la costilla que Jehová Dios tomó del hombre, hizo una mujer, y la trajo al hombre.",
      23: "Dijo entonces Adán: Esto es ahora hueso de mis huesos y carne de mi carne; esta será llamada Varona, porque del varón fue tomada.",
      24: "Por tanto, dejará el hombre a su padre y a su madre, y se unirá a su mujer, y serán una sola carne.",
      25: "Y estaban ambos desnudos, Adán y su mujer, y no se avergonzaban.",
    },
    3: {
      1: "Pero la serpiente era astuta, más que todos los animales del campo que Jehová Dios había hecho; la cual dijo a la mujer: ¿Conque Dios os ha dicho: No comáis de todo árbol del huerto?",
      2: "Y la mujer respondió a la serpiente: Del fruto de los árboles del huerto podemos comer;",
      3: "pero del fruto del árbol que está en medio del huerto dijo Dios: No comeréis de él, ni le tocaréis, para que no muráis.",
      4: "Entonces la serpiente dijo a la mujer: No moriréis;",
      5: "sino que sabe Dios que el día que comáis de él, serán abiertos vuestros ojos, y seréis como Dios, sabiendo el bien y el mal.",
      6: "Y vio la mujer que el árbol era bueno para comer, y que era agradable a los ojos, y árbol codiciable para alcanzar la sabiduría; y tomó de su fruto, y comió; y dio también a su marido, el cual comió así como ella.",
      7: "Entonces fueron abiertos los ojos de ambos, y conocieron que estaban desnudos; entonces cosieron hojas de higuera, y se hicieron delantales.",
      8: "Y oyeron la voz de Jehová Dios que se paseaba en el huerto, al aire del día; y el hombre y su mujer se escondieron de la presencia de Jehová Dios entre los árboles del huerto.",
      9: "Mas Jehová Dios llamó al hombre, y le dijo: ¿Dónde estás tú?",
      10: "Y él respondió: Oí tu voz en el huerto, y tuve miedo, porque estaba desnudo; y me escondí.",
      11: "Y Dios le dijo: ¿Quién te enseñó que estabas desnudo? ¿Has comido del árbol del que yo te mandé no comieses?",

      12: "Y el hombre respondió: La mujer que me diste por compañera me dio del árbol, y yo comí",
      13: "Entonces Jehová Dios dijo a la mujer: ¿Qué es lo que has hecho? Y dijo la mujer: La serpiente me engañó, y comí.",
      14: "Y Jehová Dios dijo a la serpiente: Por cuanto esto hiciste, maldita serás entre todas las bestias y entre todos los animales del campo; sobre tu pecho andarás, y polvo comerás todos los días de tu vida.",
      15: "Y pondré enemistad entre ti y la mujer, y entre tu simiente y la simiente suya; esta te herirá en la cabeza, y tú le herirás en el calcañar.",
      16: "A la mujer dijo: Multiplicaré en gran manera los dolores en tus preñeces; con dolor darás a luz los hijos; y tu deseo será para tu marido, y él se enseñoreará de ti.",
      17: "Y al hombre dijo: Por cuanto obedeciste a la voz de tu mujer, y comiste del árbol de que te mandé diciendo: No comerás de él; maldita será la tierra por tu causa; con dolor comerás de ella todos los días de tu vida.",
      18: "Espinos y cardos te producirá, y comerás plantas del campo.",
      19: "Con el sudor de tu rostro comerás el pan hasta que vuelvas a la tierra, porque de ella fuiste tomado; pues polvo eres, y al polvo volverás.",
      20: "Y llamó Adán el nombre de su mujer, Eva, por cuanto ella era madre de todos los vivientes.",
      21: "Y Jehová Dios hizo al hombre y a su mujer túnicas de pieles, y los vistió.",
      22: "Y dijo Jehová Dios: He aquí el hombre es como uno de nosotros, sabiendo el bien y el mal; ahora, pues, que no alargue su mano, y tome también del árbol de la vida, y coma, y viva para siempre.",
      23: "Y lo sacó Jehová del huerto de Edén, para que labrase la tierra de que fue tomado.",
      24: "Echó, pues, fuera al hombre, y puso al oriente del huerto de Edén querubines, y una espada encendida que se revolvía por todos lados, para guardar el camino del árbol de la vida.",
    },
    4: {
      1: "Conoció Adán a su mujer Eva, la cual concibió y dio a luz a Caín, y dijo: Por voluntad de Jehová he adquirido varón.",
      2: "Después dio a luz a su hermano Abel. Y Abel fue pastor de ovejas, y Caín fue labrador de la tierra.",
      3: "Y aconteció andando el tiempo, que Caín trajo del fruto de la tierra una ofrenda a Jehová.",
      4: "Y Abel trajo también de los primogénitos de sus ovejas, de lo más gordo de ellas. Y miró Jehová con agrado a Abel y a su ofrenda;",
      5: "pero no miró con agrado a Caín y a la ofrenda suya. Y se ensañó Caín en gran manera, y decayó su semblante.",
      6: "Entonces Jehová dijo a Caín: ¿Por qué te has ensañado, y por qué ha decaído tu semblante?",
      7: "Si bien hicieres, ¿no serás enaltecido? y si no hicieres bien, el pecado está a la puerta; con todo esto, a ti será su deseo, y tú te enseñorearás de él.",

      8: "Y dijo Caín a su hermano Abel: Salgamos al campo. Y aconteció que estando ellos en el campo, Caín se levantó contra su hermano Abel, y lo mató.",
      9: "Y Jehová dijo a Caín: ¿Dónde está Abel tu hermano? Y él respondió: No sé. ¿Soy yo acaso guarda de mi hermano?",
      10: "Y él le dijo: ¿Qué has hecho? La voz de la sangre de tu hermano clama a mí desde la tierra.",
      11: "Ahora, pues, maldito seas tú de la tierra, que abrió su boca para recibir de tu mano la sangre de tu hermano.",
      12: "Cuando labres la tierra, no te volverá a dar su fuerza; errante y extranjero serás en la tierra.",
      13: "Y dijo Caín a Jehová: Grande es mi castigo para ser soportado.",
      14: "He aquí me echas hoy de la tierra, y de tu presencia me esconderé, y seré errante y extranjero en la tierra; y sucederá que cualquiera que me hallare, me matará.",
      15: "Y le respondió Jehová: Ciertamente cualquiera que matare a Caín, siete veces será castigado. Entonces Jehová puso señal en Caín, para que no lo matase cualquiera que le hallara.",

      16: "Salió, pues, Caín de delante de Jehová, y habitó en tierra de Nod,[c] al oriente de Edén.",
      17: "Y conoció Caín a su mujer, la cual concibió y dio a luz a Enoc; y edificó una ciudad, y llamó el nombre de la ciudad del nombre de su hijo, Enoc.",
      18: "Y a Enoc le nació Irad, e Irad engendró a Mehujael, y Mehujael engendró a Metusael, y Metusael engendró a Lamec.",
      19: "Y Lamec tomó para sí dos mujeres; el nombre de la una fue Ada, y el nombre de la otra, Zila.",
      20: "Y Ada dio a luz a Jabal, el cual fue padre de los que habitan en tiendas y crían ganados.",
      21: "Y el nombre de su hermano fue Jubal, el cual fue padre de todos los que tocan arpa y flauta.",
      22: "Y Zila también dio a luz a Tubal-caín, artífice de toda obra de bronce y de hierro; y la hermana de Tubal-caín fue Naama.",

      23: "Y dijo Lamec a sus mujeres:Ada y Zila, oíd mi voz;Mujeres de Lamec, escuchad mi dicho;Que un varón mataré por mi herida,Y un joven por mi golpe.",
      24: "Si siete veces será vengado Caín,Lamec en verdad setenta veces siete lo será.",
      25: "Y conoció de nuevo Adán a su mujer, la cual dio a luz un hijo, y llamó su nombre Set: Porque Dios (dijo ella) me ha sustituido otro hijo en lugar de Abel, a quien mató Caín.",
      26: "Y a Set también le nació un hijo, y llamó su nombre Enós. Entonces los hombres comenzaron a invocar el nombre de Jehová.",
    },
    5: {
      1: "Este es el libro de las generaciones de Adán. El día en que creó Dios al hombre, a semejanza de Dios lo hizo.",
      2: "Varón y hembra los creó; y los bendijo, y llamó el nombre de ellos Adán, el día en que fueron creados.",

      3: "Y vivió Adán ciento treinta años, y engendró un hijo a su semejanza, conforme a su imagen, y llamó su nombre Set.",
      4: "Y fueron los días de Adán después que engendró a Set, ochocientos años, y engendró hijos e hijas.",
      5: "Y fueron todos los días que vivió Adán novecientos treinta años; y murió.",
      6: "Vivió Set ciento cinco años, y engendró a Enós.",
      7: "Y vivió Set, después que engendró a Enós, ochocientos siete años, y engendró hijos e hijas.",
      8: "Y fueron todos los días de Set novecientos doce años; y murió.",

      9: "Vivió Enós noventa años, y engendró a Cainán.",
      10: "Y vivió Enós, después que engendró a Cainán, ochocientos quince años, y engendró hijos e hijas. 11 Y fueron todos los días de Enós novecientos cinco años; y murió.",

      12: "Vivió Cainán setenta años, y engendró a Mahalaleel.",
      13: "Y vivió Cainán, después que engendró a Mahalaleel, ochocientos cuarenta años, y engendró hijos e hijas.",
      14: "Y fueron todos los días de Cainán novecientos diez años; y murió.",
      15: "Vivió Mahalaleel sesenta y cinco años, y engendró a Jared.",
      16: "Y vivió Mahalaleel, después que engendró a Jared, ochocientos treinta años, y engendró hijos e hijas.",
      17: "Y fueron todos los días de Mahalaleel ochocientos noventa y cinco años; y murió.",

      18: "Vivió Jared ciento sesenta y dos años, y engendró a Enoc.",
      19: "Y vivió Jared, después que engendró a Enoc, ochocientos años, y engendró hijos e hijas.",
      20: "Y fueron todos los días de Jared novecientos sesenta y dos años; y murió.",

      21: "Vivió Enoc sesenta y cinco años, y engendró a Matusalén.",
      22: "Y caminó Enoc con Dios, después que engendró a Matusalén, trescientos años, y engendró hijos e hijas.",
      23: "Y fueron todos los días de Enoc trescientos sesenta y cinco años.",
      24: "Caminó, pues, Enoc con Dios, y desapareció, porque le llevó Dios.",
      25: "Vivió Matusalén ciento ochenta y siete años, y engendró a Lamec.",
      26: "Y vivió Matusalén, después que engendró a Lamec, setecientos ochenta y dos años, y engendró hijos e hijas.",
      27: "Fueron, pues, todos los días de Matusalén novecientos sesenta y nueve años; y murió.",

      28: "Vivió Lamec ciento ochenta y dos años, y engendró un hijo;",
      29: "y llamó su nombre Noé, diciendo: Este nos aliviará de nuestras obras y del trabajo de nuestras manos, a causa de la tierra que Jehová maldijo.",
      30: "Y vivió Lamec, después que engendró a Noé, quinientos noventa y cinco años, y engendró hijos e hijas.",
      31: "Y fueron todos los días de Lamec setecientos setenta y siete años; y murió.",
      32: "Y siendo Noé de quinientos años, engendró a Sem, a Cam y a Jafet.",
    },
    6: {
      1: "Aconteció que cuando comenzaron los hombres a multiplicarse sobre la faz de la tierra, y les nacieron hijas,",
      2: "que viendo los hijos de Dios que las hijas de los hombres eran hermosas, tomaron para sí mujeres, escogiendo entre todas.",
      3: "Y dijo Jehová: No contenderá mi espíritu con el hombre para siempre, porque ciertamente él es carne; mas serán sus días ciento veinte años.",
      4: "Había gigantes en la tierra en aquellos días, y también después que se llegaron los hijos de Dios a las hijas de los hombres, y les engendraron hijos. Estos fueron los valientes que desde la antigüedad fueron varones de renombre.",

      5: "Y vio Jehová que la maldad de los hombres era mucha en la tierra, y que todo designio de los pensamientos del corazón de ellos era de continuo solamente el mal.",
      6: "Y se arrepintió Jehová de haber hecho hombre en la tierra, y le dolió en su corazón.",
      7: "Y dijo Jehová: Raeré de sobre la faz de la tierra a los hombres que he creado, desde el hombre hasta la bestia, y hasta el reptil y las aves del cielo; pues me arrepiento de haberlos hecho.",
      8: "Pero Noé halló gracia ante los ojos de Jehová.",
      9: "Estas son las generaciones de Noé: Noé, varón justo, era perfecto en sus generaciones; con Dios caminó Noé.",
      10: "Y engendró Noé tres hijos: a Sem, a Cam y a Jafet.",
      11: "Y se corrompió la tierra delante de Dios, y estaba la tierra llena de violencia.",
      12: "Y miró Dios la tierra, y he aquí que estaba corrompida; porque toda carne había corrompido su camino sobre la tierra.",
      13: "Dijo, pues, Dios a Noé: He decidido el fin de todo ser, porque la tierra está llena de violencia a causa de ellos; y he aquí que yo los destruiré con la tierra.",
      14: "Hazte un arca de madera de gofer; harás aposentos en el arca, y la calafatearás con brea por dentro y por fuera.",
      15: "Y de esta manera la harás: de trescientos codos la longitud del arca, de cincuenta codos su anchura, y de treinta codos su altura.",
      16: "Una ventana harás al arca, y la acabarás a un codo de elevación por la parte de arriba; y pondrás la puerta del arca a su lado; y le harás piso bajo, segundo y tercero.",
      17: "Y he aquí que yo traigo un diluvio de aguas sobre la tierra, para destruir toda carne en que haya espíritu de vida debajo del cielo; todo lo que hay en la tierra morirá.",
      18: "Mas estableceré mi pacto contigo, y entrarás en el arca tú, tus hijos, tu mujer, y las mujeres de tus hijos contigo.",
      19: "Y de todo lo que vive, de toda carne, dos de cada especie meterás en el arca, para que tengan vida contigo; macho y hembra serán.",
      20: "De las aves según su especie, y de las bestias según su especie, de todo reptil de la tierra según su especie, dos de cada especie entrarán contigo, para que tengan vida.",
      21: "Y toma contigo de todo alimento que se come, y almacénalo, y servirá de sustento para ti y para ellos. 22 Y lo hizo así Noé; hizo conforme a todo lo que Dios le mandó.",
    },
    7: {
      1: "Dijo luego Jehová a Noé: Entra tú y toda tu casa en el arca; porque a ti he visto justo delante de mí en esta generación.",
      2: "De todo animal limpio tomarás siete parejas, macho y su hembra; mas de los animales que no son limpios, una pareja, el macho y su hembra.",
      3: "También de las aves de los cielos, siete parejas, macho y hembra, para conservar viva la especie sobre la faz de la tierra.",
      4: "Porque pasados aún siete días, yo haré llover sobre la tierra cuarenta días y cuarenta noches; y raeré de sobre la faz de la tierra a todo ser viviente que hice.",
      5: "E hizo Noé conforme a todo lo que le mandó Jehová.",

      6: "Era Noé de seiscientos años cuando el diluvio de las aguas vino sobre la tierra.",
      7: "Y por causa de las aguas del diluvio entró Noé al arca, y con él sus hijos, su mujer, y las mujeres de sus hijos.",
      8: "De los animales limpios, y de los animales que no eran limpios, y de las aves, y de todo lo que se arrastra sobre la tierra,",
      9: "de dos en dos entraron con Noé en el arca; macho y hembra, como mandó Dios a Noé. 10 Y sucedió que al séptimo día las aguas del diluvio vinieron sobre la tierra.",

      11: "El año seiscientos de la vida de Noé, en el mes segundo, a los diecisiete días del mes, aquel día fueron rotas todas las fuentes del grande abismo, y las cataratas de los cielos fueron abiertas,",
      12: "y hubo lluvia sobre la tierra cuarenta días y cuarenta noches.",
      13: "En este mismo día entraron Noé, y Sem, Cam y Jafet hijos de Noé, la mujer de Noé, y las tres mujeres de sus hijos, con él en el arca;",
      14: "ellos, y todos los animales silvestres según sus especies, y todos los animales domesticados según sus especies, y todo reptil que se arrastra sobre la tierra según su especie, y toda ave según su especie, y todo pájaro de toda especie.",
      15: "Vinieron, pues, con Noé al arca, de dos en dos de toda carne en que había espíritu de vida.",
      16: "Y los que vinieron, macho y hembra de toda carne vinieron, como le había mandado Dios; y Jehová le cerró la puerta.",
      17: "Y fue el diluvio cuarenta días sobre la tierra; y las aguas crecieron, y alzaron el arca, y se elevó sobre la tierra.",
      18: "Y subieron las aguas y crecieron en gran manera sobre la tierra; y flotaba el arca sobre la superficie de las aguas.",
      19: "Y las aguas subieron mucho sobre la tierra; y todos los montes altos que había debajo de todos los cielos, fueron cubiertos.",
      20: "Quince codos más alto subieron las aguas, después que fueron cubiertos los montes.",
      21: "Y murió toda carne que se mueve sobre la tierra, así de aves como de ganado y de bestias, y de todo reptil que se arrastra sobre la tierra, y todo hombre.",
      22: "Todo lo que tenía aliento de espíritu de vida en sus narices, todo lo que había en la tierra, murió.",
      23: "Así fue destruido todo ser que vivía sobre la faz de la tierra, desde el hombre hasta la bestia, los reptiles, y las aves del cielo; y fueron raídos de la tierra, y quedó solamente Noé, y los que con él estaban en el arca.",
      24: "Y prevalecieron las aguas sobre la tierra ciento cincuenta días.",
    },
    8: {
      1: "Y se acordó Dios de Noé, y de todos los animales, y de todas las bestias que estaban con él en el arca; e hizo pasar Dios un viento sobre la tierra, y disminuyeron las aguas.",
      2: "Y se cerraron las fuentes del abismo y las cataratas de los cielos; y la lluvia de los cielos fue detenida.",
      3: "Y las aguas decrecían gradualmente de sobre la tierra; y se retiraron las aguas al cabo de ciento cincuenta días.",
      4: "Y reposó el arca en el mes séptimo, a los diecisiete días del mes, sobre los montes de Ararat.",
      5: "Y las aguas fueron decreciendo hasta el mes décimo; en el décimo, al primero del mes, se descubrieron las cimas de los montes.",

      6: "Sucedió que al cabo de cuarenta días abrió Noé la ventana del arca que había hecho,",
      7: "y envió un cuervo, el cual salió, y estuvo yendo y volviendo hasta que las aguas se secaron sobre la tierra.",
      8: "Envió también de sí una paloma, para ver si las aguas se habían retirado de sobre la faz de la tierra.",
      9: "Y no halló la paloma donde sentar la planta de su pie, y volvió a él al arca, porque las aguas estaban aún sobre la faz de toda la tierra. Entonces él extendió su mano, y tomándola, la hizo entrar consigo en el arca.",
      10: "Esperó aún otros siete días, y volvió a enviar la paloma fuera del arca.",
      11: "Y la paloma volvió a él a la hora de la tarde; y he aquí que traía una hoja de olivo en el pico; y entendió Noé que las aguas se habían retirado de sobre la tierra.",
      12: "Y esperó aún otros siete días, y envió la paloma, la cual no volvió ya más a él.",

      13: "Y sucedió que en el año seiscientos uno de Noé, en el mes primero, el día primero del mes, las aguas se secaron sobre la tierra; y quitó Noé la cubierta del arca, y miró, y he aquí que la faz de la tierra estaba seca.",
      14: "Y en el mes segundo, a los veintisiete días del mes, se secó la tierra.",

      15: "Entonces habló Dios a Noé, diciendo: 16 Sal del arca tú, y tu mujer, y tus hijos, y las mujeres de tus hijos contigo.",
      17: "Todos los animales que están contigo de toda carne, de aves y de bestias y de todo reptil que se arrastra sobre la tierra, sacarás contigo; y vayan por la tierra, y fructifiquen y multiplíquense sobre la tierra.",
      18: "Entonces salió Noé, y sus hijos, su mujer, y las mujeres de sus hijos con él.",
      19: "Todos los animales, y todo reptil y toda ave, todo lo que se mueve sobre la tierra según sus especies, salieron del arca.",

      20: "Y edificó Noé un altar a Jehová, y tomó de todo animal limpio y de toda ave limpia, y ofreció holocausto en el altar.",
      21: "Y percibió Jehová olor grato; y dijo Jehová en su corazón:No volveré más a maldecir la tierra por causa del hombre; porque el intento del corazón del hombre es malo desde su juventud; ni volveré más a destruir todo ser viviente, como he hecho.",
      22: "Mientras la tierra permanezca, no cesarán la sementera y la siega, el frío y el calor, el verano y el invierno, y el día y la noche.",
    },
    9: {
      1: "Bendijo Dios a Noé y a sus hijos, y les dijo: Fructificad y multiplicaos, y llenad la tierra.",
      2: "El temor y el miedo de vosotros estarán sobre todo animal de la tierra, y sobre toda ave de los cielos, en todo lo que se mueva sobre la tierra, y en todos los peces del mar; en vuestra mano son entregados.",
      3: "Todo lo que se mueve y vive, os será para mantenimiento: así como las legumbres y plantas verdes, os lo he dado todo.",
      4: "Pero carne con su vida, que es su sangre, no comeréis.",
      5: "Porque ciertamente demandaré la sangre de vuestras vidas; de mano de todo animal la demandaré, y de mano del hombre; de mano del varón su hermano demandaré la vida del hombre.",
      6: "El que derramare sangre de hombre, por el hombre su sangre será derramada; porque a imagen de Dios es hecho el hombre.",
      7: "Mas vosotros fructificad y multiplicaos; procread abundantemente en la tierra, y multiplicaos en ella.",

      8: "Y habló Dios a Noé y a sus hijos con él, diciendo:",
      9: "He aquí que yo establezco mi pacto con vosotros, y con vuestros descendientes después de vosotros;",
      10: "y con todo ser viviente que está con vosotros; aves, animales y toda bestia de la tierra que está con vosotros, desde todos los que salieron del arca hasta todo animal de la tierra.",
      11: "Estableceré mi pacto con vosotros, y no exterminaré ya más toda carne con aguas de diluvio, ni habrá más diluvio para destruir la tierra.",
      12: "Y dijo Dios: Esta es la señal del pacto que yo establezco entre mí y vosotros y todo ser viviente que está con vosotros, por siglos perpetuos:",
      13: "Mi arco he puesto en las nubes, el cual será por señal del pacto entre mí y la tierra.",
      14: "Y sucederá que cuando haga venir nubes sobre la tierra, se dejará ver entonces mi arco en las nubes.",
      15: "Y me acordaré del pacto mío, que hay entre mí y vosotros y todo ser viviente de toda carne; y no habrá más diluvio de aguas para destruir toda carne.",
      16: "Estará el arco en las nubes, y lo veré, y me acordaré del pacto perpetuo entre Dios y todo ser viviente, con toda carne que hay sobre la tierra.",
      17: "Dijo, pues, Dios a Noé: Esta es la señal del pacto que he establecido entre mí y toda carne que está sobre la tierra",
      18: "Y los hijos de Noé que salieron del arca fueron Sem, Cam y Jafet; y Cam es el padre de Canaán.",
      19: "Estos tres son los hijos de Noé, y de ellos fue llena toda la tierra.",
      20: "Después comenzó Noé a labrar la tierra, y plantó una viña;",
      21: "y bebió del vino, y se embriagó, y estaba descubierto en medio de su tienda.",
      22: "Y Cam, padre de Canaán, vio la desnudez de su padre, y lo dijo a sus dos hermanos que estaban afuera.",
      23: "Entonces Sem y Jafet tomaron la ropa, y la pusieron sobre sus propios hombros, y andando hacia atrás, cubrieron la desnudez de su padre, teniendo vueltos sus rostros, y así no vieron la desnudez de su padre.",
      24: "Y despertó Noé de su embriaguez, y supo lo que le había hecho su hijo más joven,",
      25: "y dijo: Maldito sea Canaán; Siervo de siervos será a sus hermanos.",

      26: "Dijo más:Bendito por Jehová mi Dios sea Sem,Y sea Canaán su siervo.",
      27: "Engrandezca Dios a Jafet, Y habite en las tiendas de Sem, Y sea Canaán su siervo.",
      28: "Y vivió Noé después del diluvio trescientos cincuenta años. 29 Y fueron todos los días de Noé novecientos cincuenta años; y murió.",
    },
    10: {
      1: "Estas son las generaciones de los hijos de Noé: Sem, Cam y Jafet, a quienes nacieron hijos después del diluvio.",
      2: "Los hijos de Jafet: Gomer, Magog, Madai, Javán, Tubal, Mesec y Tiras.",
      3: "Los hijos de Gomer: Askenaz, Rifat y Togarma.",
      4: "Los hijos de Javán: Elisa, Tarsis, Quitim y Dodanim.",
      5: "De estos se poblaron las costas, cada cual según su lengua, conforme a sus familias en sus naciones.",

      6: "Los hijos de Cam: Cus, Mizraim, Fut y Canaán.",
      7: "Y los hijos de Cus: Seba, Havila, Sabta, Raama y Sabteca. Y los hijos de Raama: Seba y Dedán.",
      8: "Y Cus engendró a Nimrod, quien llegó a ser el primer poderoso en la tierra.",
      9: "Este fue vigoroso cazador delante de Jehová; por lo cual se dice: Así como Nimrod, vigoroso cazador delante de Jehová.",
      10: "Y fue el comienzo de su reino Babel, Erec, Acad y Calne, en la tierra de Sinar.",
      11: "De esta tierra salió para Asiria, y edificó Nínive, Rehobot, Cala,",
      12: "y Resén entre Nínive y Cala, la cual es ciudad grande.",
      13: "Mizraim engendró a Ludim, a Anamim, a Lehabim, a Naftuhim,",
      14: "a Patrusim, a Casluhim, de donde salieron los filisteos, y a Caftorim.",

      15: "Y Canaán engendró a Sidón su primogénito, a Het,",
      16: "al jebuseo, al amorreo, al gergeseo,",
      17: "al heveo, al araceo, al sineo,",
      18: "al arvadeo, al zemareo y al hamateo; y después se dispersaron las familias de los cananeos.",
      19: "Y fue el territorio de los cananeos desde Sidón, en dirección a Gerar, hasta Gaza; y en dirección de Sodoma, Gomorra, Adma y Zeboim, hasta Lasa.",
      20: "Estos son los hijos de Cam por sus familias, por sus lenguas, en sus tierras, en sus naciones.",

      21: "También le nacieron hijos a Sem, padre de todos los hijos de Heber, y hermano mayor de Jafet.",
      22: "Los hijos de Sem fueron Elam, Asur, Arfaxad, Lud y Aram.",
      23: "Y los hijos de Aram: Uz, Hul, Geter y Mas.",
      24: "Arfaxad engendró a Sala, y Sala engendró a Heber.",
      25: "Y a Heber nacieron dos hijos: el nombre del uno fue Peleg, porque en sus días fue repartida la tierra; y el nombre de su hermano, Joctán.",
      26: "Y Joctán engendró a Almodad, Selef, Hazar-mavet, Jera,",
      27: "Adoram, Uzal, Dicla,",
      28: "Obal, Abimael, Seba,",
      29: "Ofir, Havila y Jobab; todos estos fueron hijos de Joctán.",
      30: "Y la tierra en que habitaron fue desde Mesa en dirección de Sefar, hasta la región montañosa del oriente.",
      31: "Estos fueron los hijos de Sem por sus familias, por sus lenguas, en sus tierras, en sus naciones.",
      32: "Estas son las familias de los hijos de Noé por sus descendencias, en sus naciones; y de estos se esparcieron las naciones en la tierra después del diluvio.",
    },
    11: {
      1: "Tenía entonces toda la tierra una sola lengua y unas mismas palabras.",
      2: "Y aconteció que cuando salieron de oriente, hallaron una llanura en la tierra de Sinar, y se establecieron allí.",
      3: "Y se dijeron unos a otros: Vamos, hagamos ladrillo y cozámoslo con fuego. Y les sirvió el ladrillo en lugar de piedra, y el asfalto en lugar de mezcla.",
      4: "Y dijeron: Vamos, edifiquémonos una ciudad y una torre, cuya cúspide llegue al cielo; y hagámonos un nombre, por si fuéremos esparcidos sobre la faz de toda la tierra.",
      5: "Y descendió Jehová para ver la ciudad y la torre que edificaban los hijos de los hombres.",
      6: "Y dijo Jehová: He aquí el pueblo es uno, y todos estos tienen un solo lenguaje; y han comenzado la obra, y nada les hará desistir ahora de lo que han pensado hacer.",
      7: "Ahora, pues, descendamos, y confundamos allí su lengua, para que ninguno entienda el habla de su compañero.",
      8: "Así los esparció Jehová desde allí sobre la faz de toda la tierra, y dejaron de edificar la ciudad.",
      9: "Por esto fue llamado el nombre de ella Babel, porque allí confundió[a] Jehová el lenguaje de toda la tierra, y desde allí los esparció sobre la faz de toda la tierra.",
      10: "Estas son las generaciones de Sem: Sem, de edad de cien años, engendró a Arfaxad, dos años después del diluvio.",
      11: "Y vivió Sem, después que engendró a Arfaxad, quinientos años, y engendró hijos e hijas.",
      12: "Arfaxad vivió treinta y cinco años, y engendró a Sala.",
      13: "Y vivió Arfaxad, después que engendró a Sala, cuatrocientos tres años, y engendró hijos e hijas.",
      14: "Sala vivió treinta años, y engendró a Heber.",
      15: "Y vivió Sala, después que engendró a Heber, cuatrocientos tres años, y engendró hijos e hijas.",
      16: "Heber vivió treinta y cuatro años, y engendró a Peleg.",
      17: "Y vivió Heber, después que engendró a Peleg, cuatrocientos treinta años, y engendró hijos e hijas.",
      18: "Peleg vivió treinta años, y engendró a Reu.",
      19: "Y vivió Peleg, después que engendró a Reu, doscientos nueve años, y engendró hijos e hijas.",
      20: "Reu vivió treinta y dos años, y engendró a Serug.",
      21: "Y vivió Reu, después que engendró a Serug, doscientos siete años, y engendró hijos e hijas.",
      22: "Serug vivió treinta años, y engendró a Nacor.",
      23: "Y vivió Serug, después que engendró a Nacor, doscientos años, y engendró hijos e hijas.",
      24: "Nacor vivió veintinueve años, y engendró a Taré.",
      25: "Y vivió Nacor, después que engendró a Taré, ciento diecinueve años, y engendró hijos e hijas.",
      26: "Taré vivió setenta años, y engendró a Abram, a Nacor y a Harán.",
      27: "Estas son las generaciones de Taré: Taré engendró a Abram, a Nacor y a Harán; y Harán engendró a Lot.",
      28: "Y murió Harán antes que su padre Taré en la tierra de su nacimiento, en Ur de los caldeos.",
      29: "Y tomaron Abram y Nacor para sí mujeres; el nombre de la mujer de Abram era Sarai, y el nombre de la mujer de Nacor, Milca, hija de Harán, padre de Milca y de Isca.",
      30: "Mas Sarai era estéril, y no tenía hijo.",
      31: "Y tomó Taré a Abram su hijo, y a Lot hijo de Harán, hijo de su hijo, y a Sarai su nuera, mujer de Abram su hijo, y salió con ellos de Ur de los caldeos, para ir a la tierra de Canaán; y vinieron hasta Harán, y se quedaron allí.",
      32: "Y fueron los días de Taré doscientos cinco años; y murió Taré en Harán.",
    },
    12: {
      1: "Pero Jehová había dicho a Abram: Vete de tu tierra y de tu parentela, y de la casa de tu padre, a la tierra que te mostraré.",
      2: "Y haré de ti una nación grande, y te bendeciré, y engrandeceré tu nombre, y serás bendición.",
      3: "Bendeciré a los que te bendijeren, y a los que te maldijeren maldeciré; y serán benditas en ti todas las familias de la tierra.",
      4: "Y se fue Abram, como Jehová le dijo; y Lot fue con él. Y era Abram de edad de setenta y cinco años cuando salió de Harán.",
      5: "Tomó, pues, Abram a Sarai su mujer, y a Lot hijo de su hermano, y todos sus bienes que habían ganado y las personas que habían adquirido en Harán, y salieron para ir a tierra de Canaán; y a tierra de Canaán llegaron.",

      6: "Y pasó Abram por aquella tierra hasta el lugar de Siquem, hasta el encino de More; y el cananeo estaba entonces en la tierra.",
      7: "Y apareció Jehová a Abram, y le dijo: A tu descendencia daré esta tierra. Y edificó allí un altar a Jehová, quien le había aparecido.",
      8: "Luego se pasó de allí a un monte al oriente de Bet-el, y plantó su tienda, teniendo a Bet-el al occidente y Hai al oriente; y edificó allí altar a Jehová, e invocó el nombre de Jehová.",
      9: "Y Abram partió de allí, caminando y yendo hacia el Neguev.",
      10: "Hubo entonces hambre en la tierra, y descendió Abram a Egipto para morar allá; porque era grande el hambre en la tierra.",
      11: "Y aconteció que cuando estaba para entrar en Egipto, dijo a Sarai su mujer: He aquí, ahora conozco que eres mujer de hermoso aspecto;",
      12: "y cuando te vean los egipcios, dirán: Su mujer es; y me matarán a mí, y a ti te reservarán la vida.",
      13: "Ahora, pues, di que eres mi hermana, para que me vaya bien por causa tuya, y viva mi alma por causa de ti.",

      14: "Y aconteció que cuando entró Abram en Egipto, los egipcios vieron que la mujer era hermosa en gran manera.",
      15: "También la vieron los príncipes de Faraón, y la alabaron delante de él; y fue llevada la mujer a casa de Faraón.",
      16: "E hizo bien a Abram por causa de ella; y él tuvo ovejas, vacas, asnos, siervos, criadas, asnas y camellos.",
      17: "Mas Jehová hirió a Faraón y a su casa con grandes plagas, por causa de Sarai mujer de Abram.",
      18: "Entonces Faraón llamó a Abram, y le dijo: ¿Qué es esto que has hecho conmigo? ¿Por qué no me declaraste que era tu mujer?",
      19: "¿Por qué dijiste: Es mi hermana, poniéndome en ocasión de tomarla para mí por mujer? Ahora, pues, he aquí tu mujer; tómala, y vete.",
      20: "Entonces Faraón dio orden a su gente acerca de Abram; y le acompañaron, y a su mujer, con todo lo que tenía.",
    },
    13: {
      1: "Subió, pues, Abram de Egipto hacia el Neguev, él y su mujer, con todo lo que tenía, y con él Lot.",
      2: "Y Abram era riquísimo en ganado, en plata y en oro.",
      3: "Y volvió por sus jornadas desde el Neguev hacia Bet-el, hasta el lugar donde había estado antes su tienda entre Bet-el y Hai,",
      4: "al lugar del altar que había hecho allí antes; e invocó allí Abram el nombre de Jehová.",

      5: "También Lot, que andaba con Abram, tenía ovejas, vacas y tiendas.",
      6: "Y la tierra no era suficiente para que habitasen juntos, pues sus posesiones eran muchas, y no podían morar en un mismo lugar.",
      7: "Y hubo contienda entre los pastores del ganado de Abram y los pastores del ganado de Lot; y el cananeo y el ferezeo habitaban entonces en la tierra.",
      8: "Entonces Abram dijo a Lot: No haya ahora altercado entre nosotros dos, entre mis pastores y los tuyos, porque somos hermanos.",
      9: "¿No está toda la tierra delante de ti? Yo te ruego que te apartes de mí. Si fueres a la mano izquierda, yo iré a la derecha; y si tú a la derecha, yo iré a la izquierda.",
      10: "Y alzó Lot sus ojos, y vio toda la llanura del Jordán, que toda ella era de riego, como el huerto de Jehová, como la tierra de Egipto en la dirección de Zoar, antes que destruyese Jehová a Sodoma y a Gomorra.",
      11: "Entonces Lot escogió para sí toda la llanura del Jordán; y se fue Lot hacia el oriente, y se apartaron el uno del otro.",
      12: "Abram acampó en la tierra de Canaán, en tanto que Lot habitó en las ciudades de la llanura, y fue poniendo sus tiendas hasta Sodoma.",
      13: "Mas los hombres de Sodoma eran malos y pecadores contra Jehová en gran manera.",

      14: "Y Jehová dijo a Abram, después que Lot se apartó de él: Alza ahora tus ojos, y mira desde el lugar donde estás hacia el norte y el sur, y al oriente y al occidente.",
      15: "Porque toda la tierra que ves, la daré a ti y a tu descendencia para siempre.",
      16: "Y haré tu descendencia como el polvo de la tierra; que si alguno puede contar el polvo de la tierra, también tu descendencia será contada.",
      17: "Levántate, ve por la tierra a lo largo de ella y a su ancho; porque a ti la daré.",
      18: "Abram, pues, removiendo su tienda, vino y moró en el encinar de Mamre, que está en Hebrón, y edificó allí altar a Jehová.",
    },
  },
};

export default bible;
